### ISSUE TITLE
FreeDM should have its own music

### ISSUE THREAD

**Issue by fragglet** [freedoom/freedoom#10]
Currently FreeDM uses the same music as Freedoom. Some of the music tracks are okay for deathmatch but others are too slow. For deathmatch levels we want something more fast-paced and rockin'.

It might be possible to selectively reuse some of the existing music tracks to use for FreeDM to put together a more appropriate soundtrack.

**Comment by mc776** [comment]
After #1009 it seems DM14 and Map32 are the only duplicates left.

**Comment by rostuhan** [comment]
Oh, you've meant D_DM14 and D_DM32.

**Comment by mc776** [comment]
huh, well I guess there are no duplicates between FreeDM and singleplayer now.

If someone does want to do a new track for one of those DM maps this is not meant to discourage that but I think we can close this issue, subject to someone else verifying this because I do *not* trust myself to check 32x27x32 possible combinations right now.

**Comment by mc776** [comment]
Just did another round of checks, can't find dups of anything at all, I think this is safe to close.

**Comment by mc776** [comment]
I just realized while looking at #1125:

> --FreeDM--
> Title: (same as Phase 2)
> Intermission: (same as Phase 2)
> Story: (same as Phase 2)
