### ISSUE TITLE
e4m7,9 & e3m7 issues/suggestions

### ISSUE THREAD

**Issue by nful2** [freedoom/freedoom#1028]
1. E4m7 - zombie is placed mistakenly? https://github.com/freedoom/freedoom/assets/100768714/87416eac-4e0d-48db-8a20-d667d6a7d14f

3. E4m7 - unable to go forward from the right https://github.com/freedoom/freedoom/assets/100768714/a707fd24-f00c-4920-a594-1a522145f000

4. E4m9 - In the secret, unable to go down unless enemies move away https://github.com/freedoom/freedoom/assets/100768714/e43991f6-89c5-4484-9144-6ece8252abe7

**Comment by mc776** [comment]
1. That zombie can attack and be attacked after the nukage is lowered. I think it would be a good idea to make that a non-run-ending trap though, by having it lower to just -24 instead of -40 (and why is the other one -48?)

2. Absolutely baffling. Going upwards it feels just like someone had flagged line 1544 as impassable but that is not what's going on. Moving the lines doesn't help either...

Will take a look at 3 after I've figure out 2.

**Comment by nful2** [comment]
@mc776 Have found one more in e3m7 - 4th pain lord didn't teleport during cyberdemon fight

https://github.com/freedoom/freedoom/assets/100768714/73957015-0c7f-4cc0-9fb8-881baf9e9a18
