### ISSUE TITLE
MAP31 route to MAP32 is pure RNG

### ISSUE THREAD

**Issue by GrayFace** [freedoom/freedoom#1053]
MAP31 involves facing a Cyber Daemon and walking around it in a tiny room to reach a teleporter. Over 95% of the time it ends up blocking your path and then you're dead, at least with fast monsters. This is a level design bug.

**Comment by mc776** [comment]
Which specific room is the issue? And what mods are you loading?

**Comment by GrayFace** [comment]
The daemon in question is x550 y0 z0. No gameplay mods: `"./gzdoom.exe" -iwad "../freedoom2.wad" -file "../midi/menu" "../bonus/HDskiesD1.pk3" +sv_cheats 1 -fast`
(I'm normally playing with mods, but for this level I wanted to experience it the original way.

**Comment by mc776** [comment]
Oh, the supersecret level entrance. Yeah, yikes.

I don't know what to do with it that doesn't make it less... "secrety"...

**Comment by mc776** [comment]
Here's one attempt: create an optional shootable switch to let the tripod leave that area.
[map31.wad.zip](https://github.com/freedoom/freedoom/files/12267684/map31.wad.zip)

It's still a big test of one's patience to hit the switch instead of the tripod but at least you're not actively trying to move into its space at the same time.

**Comment by mc776** [comment]
Moving that shootable switch a bit forward to make it easier to hit:
[map31.wad.zip](https://github.com/freedoom/freedoom/files/12319206/map31.wad.zip)

This also gets rid of orthogonal lines with tentacle textures so you don't see those stripes of fake contrast cutting through the organic shapes.

**Comment by mc776** [comment]
This version moves some lines around to mitigate some texture alignment issues:
[map31.wad.zip](https://github.com/freedoom/freedoom/files/12341642/map31.wad.zip)

Absent any objections I'll add this to one of the outstanding minor level fix PRs.

**Comment by mc776** [comment]
[map31.wad.zip](https://github.com/freedoom/freedoom/files/12346863/map31.wad.zip)
i hate secret sectors

**Comment by GrayFace** [comment]
The fix I was imagining is just placing the teleporter on a side of Tripod's box instead of on the back, so that you still move to Tripod's space quickly, but then just strafe to the left or right.

**Comment by GrayFace** [comment]
With this fix how do you kill the Tripod after releasing him? There's only enough ammo for 1 final Tripod.

**Comment by mc776** [comment]
by not pistol starting i guess.

i think of this fix as a tradeoff for an "easy" way to map32, because *all* of the secrets on this map are the same kind of problem.

**Comment by mc776** [comment]
I'd also try harder to address this but frankly I hate this level a lot and someone who actually enjoys it should—come to think of it, as the person who pays attention to this enough to post about it, I'm going to take your advice.

Here's the level with that teleporter to the side: https://github.com/mc776/freedoom/blob/5c3a733f726417a0a150fcc92fa8baabba1ed5de/levels/map31.wad

**Comment by Talon1024** [comment]
Regarding MAP31, the original author of that map [tried to address ](https://www.doomworld.com/forum/topic/93288-phase-2-map12-map-20-plus-secret-maps-management-thread/?page=2&tab=comments#comment-1728630) some issues with the level, as well as give it a new paint job, but that was many years ago, and it seems like nobody maintaining Freedoom at the time noticed this.

**Comment by mc776** [comment]
Finally got a chance to look.

- Holy shit I thought *I* was the one who broke the map by merging "extraneous" sectors! Instead it turns out that's author-original... I guess I should change this back.
- Same "I thought I broke this somehow but it turns out to be authorial intent" comment for the weird skewed lines and mismatched SUPPORT2 textures in the switch room. I don't think this is worth reverting.
- It's missing the new supersecret exit system of the current version of the map.
- Normally I love the Aquatexes but frankly this is not an improvement over the unity of the original METAL2 theming. It actually feels like I'm playing an earlier alpha version of the map.
- I have no idea what this "tiny hint" for the red card is. At all... until I compare it with the current map and see the addition of the blood pool. There's no way anyone would get this if they didn't know the earlier version's decoration placement!
- The fix to the OP issue implemented here is exactly what I initially tried: making that chamber slightly wider but keeping the teleporter at the back. It doesn't actually help the fundamental problem that it's pure RNG whether or not the tripod will get in your way anyway no matter how well you time it initially. Putting the teleporter on the side instead of the back is the correct solution - once you've timed the initial entry, your own hitbox prevents the tripod from stepping in and ruining your work, so all that's left is to actually reach the teleporter before it can rocket you.

I'll re-merge those sectors and do a few texture cleanups with this stuff in mind.

**Comment by GrayFace** [comment]
Here I've made it work, with over 50% success rate: 
[map31.zip](https://github.com/freedoom/freedoom/files/12385443/map31.zip)
I've moved it closer to get rid of the randomness and this also makes it less "in your face". I also gave it the same "secret walk-through wall" treatment as the one on the other side.

**Comment by mc776** [comment]
while increasing the randomness of anyone ever finding that without already knowing it's there...

**Comment by GrayFace** [comment]
That's debatable. The player is looking for something when opening that tripod cage. As long as it's not in the back, it's reasonable.
I was also thinking of placing the walk-through wall here:
![screenshot 379](https://github.com/freedoom/freedoom/assets/5989806/57b0bc57-dd78-42da-bcf1-988154fec3d2) (here I moved the teleporter closer along X axis, but turns out there's a limitation on floor/ceiling alignment)

P.S. Freedoom is doing a much better job than Doom at making secrets not random.

**Comment by mc776** [comment]
I've incorporated the change: https://github.com/mc776/freedoom/blob/d52f82cf4141edd83db538b1da8e5406c7ae5184/levels/map31.wad
