### ISSUE TITLE
Octaminator not telegraphed enough

### ISSUE THREAD

**Issue by MerrittK** [freedoom/freedoom#1122]
Because the Octaminator is shorter then it's doom equivalent, it doesn't have to lean forward to attack, this change makes it easer to miss it's attack in the heat of battle, making it harder to dodge.

**Comment by mc776** [comment]
one walking frame (B)
![skelb1e1](https://github.com/freedoom/freedoom/assets/24984517/90a5561b-aa24-463a-bd42-0420704e3588)

first frame in missile state (J)
![skelj1](https://github.com/freedoom/freedoom/assets/24984517/9734fccb-7f75-4fb2-85c6-db0ad578ec4c)

**Comment by MerrittK** [comment]
It isn't just absolute distance. Notice that the Octaminator body just moves downwards, while the revenant's body leans. In addition, The Octaminator tentacles are visually complex compared to the legs, so the movement is harder to follow.

See how much the profile changes when the original revenant is moving?
https://youtu.be/P7KndRlL1Ak?si=9hDaTXAEFSR4x4Fe

In comparison, the Octaminator's attacks just don't have the same follow-through. The punch in particular feels limp, because he isn't throwing as much of his shoulder into it. 

Part of it is just a difference with the source. The revenant was a model, so they could rotate and pose it, while hand drawn sprites don't support the huge perspective shift.

It might just be an issue for me getting used to the new sprites, but I wanted to express it anyway.

**Comment by MerrittK** [comment]
The revenant is a pretty unsubtle monster in the original, which fits for the extreme damage he can deal.

**Comment by MerrittK** [comment]
The sprite is amazing, and still way better then the old dark soldier. 

Part of it is just the sound volume, The sounds themselves are really good, but they aren't quite loud enough to be heard over other enemies.  They don't have to be earsplittingly loud like their OG cousin, but it could do to be a smidge louder.

Thanks for taking the time to listen to my concerns. I am visiting the github more often because I am planning out a PWAD specifically targeted towards freedoom. (The nice thing about the git build process is that palette duplicates are guaranteed to be unused, giving me a lot more freedom to remap the colors.)

**Comment by Ferk** [comment]
> Notice that the Octaminator body just moves downwards, while the revenant's body leans. In addition, The Octaminator tentacles are visually complex compared to the legs, so the movement is harder to follow.

I think the Octaminator is also leaning, or at least I feel that's what the intention was (if you look at the torso, it's shorter due to perspective and you can see an abrupt cut indicating the chest is protruding). Though I agree it's not transmitted very well, and the way the lower torso is fully lit doesn't help transmit a feeling of depth.

However, I'm not sure if tweaking the lighting to give it more depth and make the leaning more apparent would really help with the telegraphing. As it stands, the attack phase has actually a more drastic change in color / brightness due to the cannons revving up than the original Revenant attack frame.

I feel the reason the original might feel more telegraphed is because it's a very thin skeleton with long arms and legs, so it's easy to perceive its movements as exaggerated. But the octaminator is thick.. more muscular, and him flexing his arms is not as big of a visual change than the skinny floppy arms/legs contracting for the attack.

**Comment by MerrittK** [comment]
Honestly, it might have just been me... I am more used to the originals.

I tried playing a map with a rev and an octa back to back, and there isn't much of a difference, sound and spriteing are both super similar. - I just misremembered revenants as being more telegraphed then they were, because I am more used to them. Revenent trauma hasn't caught up to the freedoom design.

It could probably still stand to be improved a bit, especially for newer players, but it isn't as much of an issue as I made it out to be.
