### ISSUE TITLE
Delegate to an active maintainer the ability to post a release

### ISSUE THREAD

**Issue by mc776** [freedoom/freedoom#1259]
At this point with that last batch of updates everything is done and ready to go. It's not perfect but if we wait for perfection there will literally be no release.

If the wait is for new mastermind graphics I strongly advise against that.

All other outstanding issues right now are long-term or no solution is known and available to be implemented. All we need now is someone who has both the time+ability *and the authorization and credentials* to complete the actual release itself.

My understanding is that someone needs to be given the authority to:
1. post the release on this repository and
2. update the website.

Everything we need for that should be described in #400 and I believe @selliott512 can fill in any gaps.

If there's anything else (e.g., updating the Debian repository, I have no idea how that works) that should be dealt with too, but these two are the minimum after which we can say "this is the latest release" and an unsophisticated user can go to the website and download it.

**Comment by selliott512** [comment]
That's a good summary, @mc776 . I'd be happy to be the person who gains those permissions since I've been somewhat like a release lead for 0.13.0, which we can make more official, but I'd understand if someone else is chosen.

In addition to what you listed the git tags that will be created need to be signed. I could do it, but ideally it should be a well know person in the FD community.

I don't know of addition work with regard to the "Debian repository", but if there is I can add it to #400 . My hope is for #400 to describe everything that needs to done for a release.

**Comment by northivanastan** [comment]
If I understand things correctly, updating Freedoom in the Debian repository is up to the Debian maintainer for Freedoom, which according to the distro's website would be Fabian Greffrath and the Debian Games Team. I suppose someone could bother Fabian about it, but otherwise I doubt anything needs to be done prior to release.
