### ISSUE TITLE
Rename Episode 2

### ISSUE THREAD

**Issue by mc776** [freedoom/freedoom#1327]
https://github.com/freedoom/freedoom/pull/1326#issuecomment-1927531629

I'm so glad someone else brought this up. These haven't been "military" and scarcely "labs" in forever.

As far as FD's existing plot goes, this area needs to:
- be known for having a starport
- be connected to the prison outpost and the protag needs to know about it

Of course, even these aren't necessarily set in stone - the texts can easily be rewritten so that the protag takes that teleporter and finds themselves in an unknown location.

As far as E2's aesthetic goes, it is:
- techbase with lots of alien monster stuff enmeshed into it
- covered with water and vines, very overgrown

Maybe it's another outpost on the same planet, but more equatorial?

**Comment by unithecutie** [comment]
It barely even resembled "military labs" at first: (0.9, when it was named)
the original version of E2M1 was like an "implant" of sorts inside of ancient **ruins**.
the old E2M2 was trying to be a factory/power plant it seems - would ask the author if it weren't for this:
![image](https://github.com/freedoom/freedoom/assets/139153158/982a14bf-d42f-4fa1-8a3a-113ce18656c9)
the old E2M3 has similar theming to E2M1, but to a much lesser extent.
the old E2M4, yes, this is a military lab.
the old E2M5, this is a military stronghold, but not so much a lab
E2M6 didn't exist in that version
E2M7 didn't exist in that version
E2M8 isn't even a containment cell, otherwise the cybies wouldn't be free-roaming.
E2M9 is a mishmash of old maps (G0dCells' 0.7 E1M8, Archfile's unused E2M8 and unique parts by Xindage)

**Comment by Xindage** [comment]
My plan was having all maps using different themes, but we still need the maps done before we do some theme swap in them, my proposal idea was to this episode be in an red mist where the aliens collect several pieces of other worlds (reason on why I would like to have e2m9 as Egypt) I kinds discussed it on discord a long time ago

**Comment by mc776** [comment]
Here's one idea: "Corrupted Ruins"
```
E1TEXT = Free at last from that dreadful outpost!\n\
         But you're still stuck on this rock, with\n\
         AGM and all their monstrous "experiments."\n\
         Best not to dwell on what evil horrors\n\
         they were going to create from you...\n\n\
		 Damn alien teleporter ate your gear.\n\
         The air is hot and muggy, and smells of\n\
		 strange, intoxicating vegetation. You see\n\
         what looks like AGM corpo tech patched\n\
         over old, overgrown alien structures.\n\
         It's too too advanced to be the work of\n\
		 the outpost goons, meaning there must be a\n\
         starport nearby. To Earth. To freedom.\n\n\
         One way back - through the Corrupted Ruins.
```
and proof that it doesn't spill over:
![DOOM00](https://github.com/freedoom/freedoom/assets/24984517/92a46ac5-d735-4bdb-837e-acddc7059d2f)

**Comment by unithecutie** [comment]
"Outpost Outbreak"
_"Corrupted Ruins"_
"Event Horizon"
"Double Impact"

Meh, still a bit bland in my opinion, but it works leagues better than "Military Labs".

**Comment by mc776** [comment]
Yeah, we should do better, though I still think the endtext is in the right direction.

E3 endtext just ends with "Horizon" not "Event Horizon" so we've got some wiggle room.

The implied story behind this revised endtext is that we're looking at a reverse of D2 - it's the human corpos who are invading and changing an ancient alien facility to suit their needs rather than the other way around. Maybe some kind of play on EEE is in order?

**Comment by unithecutie** [comment]
Human corpos siphoning resources off of ancient alien facilities; I love that idea.

**Comment by unithecutie** [comment]
"Anti-Pattern" rolls right off of the tongue, I like it.

**Comment by mc776** [comment]
![DOOM00](https://github.com/freedoom/freedoom/assets/24984517/80970ba1-90a3-4cb2-a55c-8ec408b154bb)

**Comment by unithecutie** [comment]
Oh, hell yeah.

**Comment by KukoBerry** [comment]
While I do agree that "Anti-Pattern" sounds like a cool episode name (would make for a wicked metal album title!), I personally don't feel like it means much of anything compared to the theming of the map set... Plus the last paragraph of the episode 1 ending blurb sounds kind of awkward, maybe because of that 😔 not to discredit M's suggestions tho

Maybe something with 'infection' or some sort of metaphor for AGM being a 'foreign body' forcibly inserted into the planet, with its putrid vines acting as its immune system of sorts?

**Comment by mc776** [comment]
"Extend, Extinguish" might actually work for that... except any attempt to get *that* into the endtext is likely to be even more forced than anti-pattern.

something something ruins... ::looks up "ruins" on Wikiquote::

Another suggestion:
Episode name: [Ruin Upon Ruin](https://www.poetryfoundation.org/poems/45738/paradise-lost-book-2-1674-version)
Endtext same, except replace the last lines with:
```
         Just gotta hope that ship will launch\n\
         from these routed, infested ruins...
```

**Comment by unithecutie** [comment]
"Ruin Upon Ruin" could work! Again, much better than _Military Labs_ but just a slight bit more bland than _Anti-Pattern_
Also, I think it would be best if we merged #1326 first?

**Comment by UltimateCraneo** [comment]
Wouldn't the aliens practicing self-defense against the corpos technically make the player the bad guy (atleast for phase 1)

**Comment by mc776** [comment]
Player is clearly another victim of the corpos. First paragraph of endtext was unchanged in that respect.
