### ISSUE TITLE
Music volume is inconsistent

### ISSUE THREAD

**Issue by Blastfrog** [freedoom/freedoom#157]
Just as the title says. Some songs are about right, some are too loud, and some are too quiet. It'd be nice to standardize the volume at half amplitude.

**Comment by milasudril** [comment]
Hmm, I wonder if it is possible. It seems like the signal levels in MIDI is not standardized. I have one synth with very quiet Clean Guitar (TBS Montego Wavetable), and another with a much louder sound (Casio CTK-631). Since this is the case, details in the mix screw up, and the total volume may work well on one synth, and not on another. Also the music should follow the theme in the map, and some maps should be more quiet than others.

**Comment by mc776** [comment]
Are there any tracks that stand out at this point? This issue is almost 9 years old and I'm not sure if there's anything that's been left the same since this was first opened.

**Comment by unithecutie** [comment]
It would only really be Jute's tracks that still have this problem, but there's only one of them left and that one's volume is normal.
This issue can be closed.

**Comment by Blastfrog** [comment]
Nine years? Stop making me feel so old! :P Yeah, this issue can certainly be closed, I've noticed no issues as of late regarding this.

**Comment by unithecutie** [comment]
> Nine years?

#10 lasted almost 10 years. :P
