### ISSUE TITLE
Plutonia compatibility has issues

### ISSUE THREAD

**Issue by chungy** [freedoom/freedoom#194]
Loading up Plutonia's MAP30 and getting to the Icon of Sin area highlights a couple problems: the brain textures (DBRAIN*) is not displayed correctly, and there are switches misaligned for the central elevator.

Not a blocking issue for 0.10

**Comment by fragglet** [comment]
The misalignments are because Freedoom's SW1BRN1 texture is wrong.

This is how Doom 1's SW1BRN1 is defined:

    SW1BRN1                 64      128
    *       WALL02_2        0       56
    *       WALL02_2        0       0
    *       SW3S0           16      75

But Doom 2's SW1BRN1 is defined like this:

    SW1BRN1                 128     128
    *       WALL62_1        0       0
    *       SW1S0           48      72

For some reason Freedoom is using the Doom 1 definition rather than the Doom 2 one. This is actually a more general compatibility problem rather than being Plutonia-specific. We should probably make the SW1BRN1 definition conditional based on the IWAD type.

**Comment by Gaerzi** [comment]
Several switches are copies of SWxBRCOM in Doom II because they aren't used in any of the IWAD levels. Using the Doom definition makes more sense as it provides more options for mappers.

[Doom Wiki reference](http://doomwiki.org/wiki/Switch)

**Comment by fragglet** [comment]
It's a strange use case to be sure, but this isn't really a Plutonia problem but rather a more general compatibility problem. What you said makes sense but ultimately there are plenty of Doom 2 PWADs out there using the Doom 2 definitions of those textures. Any WAD that uses SWxBRN1 is likely to have the same problem.

**Comment by Gaerzi** [comment]
It's just that between that and the decision to go vanilla compatible (meaning no Boom lumps for extra switches) the switch options become quite limited, as four useful switch textures are reduced into clones of BRCOM.

**Comment by fragglet** [comment]
Yup, and that kinda sucks. But the alternative is to break compatibility which seems worse.

This is just one of the drawbacks of moving to Vanilla-compatible I guess.

**Comment by Blastfrog** [comment]
I'd prefer to break cosmetic compatibility just a little bit in favor of using all available switch textures in all IWADs.

**Comment by watchmakerful** [comment]
>>It's just that between that and the decision to go vanilla compatible (meaning no Boom lumps for extra switches)
Freedoom has much more vanilla incompatibilities, e. g. generalized elevator actions in MAP11.

**Comment by Gaerzi** [comment]
Irrelevant. Yes, at the moment the maps are for Boom compatibility, but [the decision has been taken to go vanilla compatible](https://www.doomworld.com/vb/freedoom/85134-freedoom-1-0-will-be-vanilla-compatible/) which means that the maps will be edited down to vanilla features only eventually.

My point being that because of this decision we're not going to have ANIMATED and SWITCHES lumps that would have been possible to get more variety in switches and animated textures/flats to compensate for the loss of SW*BRN1 that's actually a BRN1 and so on.

**Comment by fragglet** [comment]
@Blastfrog - I understand the desire for more usable switch textures, but is there any actual pressing need? An example would be if Freedoom level authors were asking for more switch textures. If it's just a case of "it would be nice to have more of a variety of textures", it's hard to see why that's worth breaking PWAD compatibility.

If there genuinely is demand for it, one option might be to change the duplicate textures so that they have different, mostly-compatible, backgrounds. That would be a better solution that would retain compatibility, instead of using the Doom 1 versions of the textures which have different sizes and are therefore inherently incompatible.

**Comment by Proluiz** [comment]
this is not the only poblem too... i think of we need few pwad correction to be compatible whit all iwads, for exemple:
fireblu1 issue in plutonia.
Switchs issues in doom2.
WFall issues in TNT.

i think of its impssoble to cover all these solutions in a single iwad.

**Comment by NickZ** [comment]
As explained in #435 and #406, we can't fix the DBRAIN animation without breaking other animated textures. This goes for the issues mentioned above as well. Fortunately, as #435 explains, most final doom pwads have their respective texture definitions in them as well, so they will still be compatible.

Also, the textures on the switches seem to be fine now. I think that's all we can do for this issue?

**Comment by adil25** [comment]
@NickZ @fragglet etc...i am new to the world of Doom/FreeDoom etc....i understand textures but what does switches means? i have started to understand the technical terms so please can you tell me what are switches, plutonia, vanilaa, and the difference between PWAD and IWAD? please forgive me if it looks a bit nonsense.... Thanks

**Comment by NickZ** [comment]
Switches refers to the actual switches that you press in the game. 

Plutonia is one-half of Final Doom; it has its own unique texture set that presents problems with freedoom compatibility with custom WADs that use its textures (like Plutonia 2).

Vanilla refers to the original DOS game engine, as opposed to one of the source ports (like GZDoom and Odamex). Freedoom aims to have compatibility with Vanilla Doom.

As for PWAD and IWAD, take a look at the doomwiki: https://doomwiki.org/wiki/PWAD 
 https://doomwiki.org/wiki/IWAD

If you'd like to learn more, I'd recommend browsing the doomwiki; it has a lot of technical details.

**Comment by adil25** [comment]
@NickZ .......Thanks alot ......
