### ISSUE TITLE
Remove empty space from missile sprites

### ISSUE THREAD

**Issue by Danfun64** [freedoom/freedoom#200]
@Blastfrog said that the recent commit that raised the missile sprites "isn't correct, only angles 1 and 5 should use 13 as a vertical offset, the rest need to use 10."

For whatever reason, nobody else noticed this issue.

**Comment by NickZ** [comment]
No, I didn't miss this. The trails are calculated from the top of the sprite minus the offset, and because the side missile sprites have an empty space around them, they had to have a higher offset to fix this. it didn't look right with the sprites being raised only 3 pixels.

To totally fix this, the sprites themselves have to be modified to removed the empty space.

**Comment by Danfun64** [comment]
Thanks for the explanation. I guess that this issue will stay opened until the empty space is removed...
