### ISSUE TITLE
Error: P_InitPicAnims: bad cycle from SLADRIP7 to SLADRIP3

### ISSUE THREAD

**Issue by VGAce** [freedoom/freedoom#252]
Error: P_InitPicAnims: bad cycle from SLADRIP7 to SLADRIP3

specific to freedoom it works with doom2  wad
tested with crispy-doom
darken.wad 
https://www.doomworld.com/idgames/levels/doom2/megawads/darken

**Comment by Voros2** [comment]
Some of the TNT textures (including SLADERIP) aren't implemented due to conflicts. It says so in textures.cfg

**Comment by NickZ** [comment]
Yeah, we can't implement the animated textures from Final Doom due to compatibility issues with doom2. We can't fix this. All I can suggest is that you put the Plutonia texture definitions in the pwad itself to fix the issue.

https://github.com/freedoom/freedoom/commit/96ca8bf67bc4eec197f876afcf4624481fb6bf10
