### ISSUE TITLE
floor4_8 not matching with metal1

### ISSUE THREAD

**Issue by Voros2** [freedoom/freedoom#342]
On the very first level of Phase 2, this is noticeable. The hexagonal flat doesn't match up with the hexagonal patch. This was brought up a long time ago by Protox on Doomworld: https://www.doomworld.com/vb/freedoom/90360-floor4-8-is-not-matching-whit-metal1-anymore/
Apparently, the flats were donated by Sodaholic in https://github.com/freedoom/freedoom/pull/215 
To be frank, I say that you guys either revert back to the old flats, or use the current flat to serve as the patch too (hey that's pretty good workaround). But as MrFlibble said on Doomworld, the original textures seemed to fit better with the rest of the textures in Freedoom. 
What do you think should be done?

**Comment by fragglet** [comment]
`WALL03_7` should always match `FLOOR4_8` I think. Maybe we should encode this into the build system explicitly? Along with any other wall/flat matches like this one.

In the mean time, just copying the new `floor4_8.gif` over `wall03_7.gif` should fix the immediate problem.

**Comment by Voros2** [comment]
Yes, that would simplify the problem for future updates. 

Yes it would fix the problem. But does this new, smoother, softer flat match well with the other not smoother or softer textures?

**Comment by AXDOOMER** [comment]
Just noticed that a texture was looking weird on my map and it was because this texture was replaced. I don't think it looks good with other Freedoom textures, because it doesn't have that ruggedness that other textures have. It's too smooth, too flat, it doesn't have any relief like other textures seem to have (even though Doom has no bump mapping). The original textures for the hexagonal flats and wall were better.
