### ISSUE TITLE
C2M1's difficulty seems wildly out of alignment

### ISSUE THREAD

**Issue by fluffymormegil** [freedoom/freedoom#379]
The difficulty of C2M1's opening sections feels inappropriate for the first map of an episode, unless it is an episode directly aimed at people who think PLUTONIA.WAD MAP01 was too gentle.

**Comment by Voros2** [comment]
Its nowhere near Plutonia's level of difficulty if you ask me.

**Comment by chungy** [comment]
It is still fairly tough, giving the player spectres with only a pistol at the beginning. We ought to rearrange the episode.

**Comment by Voros2** [comment]
Replacing the spectres with, say, imps or zombies should do it then, since he only says the opening section is difficult.

**Comment by fluffymormegil** [comment]
It's not so much the spectres - I don't particularly care about getting 100% kills, and there's enough room to dance around them - as the blind drop into the field of fire of an army of hitscanners while armed with only the pistol.

**Comment by Voros2** [comment]
I never found myself being confronted by an "army" of hitscanners. Upon jumping down, I kill the few hitscanners present. These hitscanners tend to be far away from the player, so not much damage taken. Plus, then you can pick up a shotgun from the dead shotgun zombie. Upon firing, other hitscanners become alerted and come in one-by-one, but never as a whole. So basically, I'm fighting waves of only a few zombies for a short amount of time. Using a shotgun.

**Comment by Proluiz** [comment]
actualy this map is not that hard, for the skill called hard its very confortable lot of monsters and they come one by one so its easy to dispatch them, in medium the map is actaaly very easy to my flavors, just 20% less monsters more health and early acess to guns, Easy is a "piece of cake", an initial shotgun acess and chaingun just in left side of poll plus near -40% of enemys make it extreme fine fow who "dont know how to play" so i see no poblems at dificult balance.

Since from when i begin mapping i used a logic of someone tell me (i dont remenber who told anyway)

Easy, is for very begginers, player not familiar whit the game at most, extra health and ammo too and low tiers enemys.
Medium, usual players give them challenges whit proper equipment.
Hard, Expert gameplays, hard challenges+traps with bigger amounts of enemys, extra ammo for compensate the difficult and high tiers of enemys present.

**Comment by Voros2** [comment]
I admit this map is bit difficult at times, and could use some nerfing, such as lowering the number of shotgun zombies.

**Comment by ReakutheCrate** [comment]
Honestly, the map feels more suited for episode 3 than 2, the spectres at the beginning are a little much, along with how many shotgunners there are in the beginning, It's a fair bit disperportionate where it is.
