### ISSUE TITLE
deh / bex override

### ISSUE THREAD

**Issue by JimFlasch** [freedoom/freedoom#429]
I have been playing the pwad invasion.wad with freedoom pahse one via GZDoom (latest version) and have noticed that the FreeDoom iwad's deh / bex lump loads last, overriding the pwad's accompanying deh file, which loads _before_ the iwad's lump. Why is that happening?

**Comment by AXDOOMER** [comment]
Source port bug?

**Comment by Voros2** [comment]
Looks like a matter of priority rather than Freedoom related. The source port might have made the IWAD's DEHACKED lump a bigger priority than the PWAD's DEHACKED lump. 

Either it's the source port's fault, the invasion.wad DEHACKED lump is faulty/corrupt/incorrect, or your loading the files in the wrong order.

**Comment by chungy** [comment]
Please report it to Graf as a GZDoom bug.
