### ISSUE TITLE
Re-enable travis-ci builds

### ISSUE THREAD

**Issue by fragglet** [freedoom/freedoom#473]
The dependency on deutex 5.0 broke continuous integration. We should re-enable it once the new version is available.

**Comment by NickZ** [comment]
This will likely have to be solved with Docker images, as travis is still stuck on ubuntu 14.04 and doesn't look like it will be updated any time soon

**Comment by NickZ** [comment]
We will want to do Docker images anyway, since we have a pull request coming that will have the makefile generate wad-diff images; it has a dependency on a third-party app. It would be really nice to be able to generate a wad-diff image for every pull request that has a level in it and automatically post it using travis.
