### ISSUE TITLE
How to disable main menu background screen red text?

### ISSUE THREAD

**Issue by DeusMaveriX** [freedoom/freedoom#508]
It overlaps with the settings texts

**Comment by Calinou** [comment]
This is something your source port should handle. By default, GZDoom comes with a transparent yellow background when the menu is opened. However, it can interfere with Freedoom's help text background since it's pretty subtle. You can increase it in the **Display settings** by increasing menu dim and changing its color to something like black.

![gzdoom_dark_menu_background](https://user-images.githubusercontent.com/180032/32746237-3f393c66-c8b5-11e7-89e9-77ff6b58f894.png)

**Comment by DeusMaveriX** [comment]
Thank you. Also I found that pressing tilde for console will freeze the artwork background, which makes for easier reading

**Comment by Proluiz** [comment]
Anyway if you guys wanna a different color for credits I Did few options:

Original red:
![CREDIT](https://user-images.githubusercontent.com/6380147/64303573-27e9fe80-cf5f-11e9-9fb0-25acec95208f.png)

Green:
![CREDIT_G](https://user-images.githubusercontent.com/6380147/64303568-2587a480-cf5f-11e9-8f59-257260d2e763.png)
Blue:
![CREDIT_B](https://user-images.githubusercontent.com/6380147/64303564-228cb400-cf5f-11e9-8014-61d5572df079.png)
