### ISSUE TITLE
Waterfalls of MAP25 won’t animate

### ISSUE THREAD

**Issue by Litrivin** [freedoom/freedoom#518]
Paging @Talon1024 ...

It seems MAP25 contains waterfalls which won’t animate at all, because the respective linedefs (3611, 3602, 3580 and 3578) have WFALL texture instead of the proper one: WFALL1. A simple search and replace should fix this, I guess.

**Comment by Talon1024** [comment]
You're right. I thought I fixed that, though.

I'll go through all the maps and replace any {W,S,B}FALL textures with their animated equivalents. I'm also going to remove the {W,S,B}FALL textures from the build configuration because they are leftovers from when Freedoom still had the goal of being Boom-compatible (and Boom has vertical scrolling line specials), and therefore not needed anymore.

**Comment by Litrivin** [comment]
Well done.

Also, it seems there is another animation affected: FIRELAVA. For example, C3M2 has a mix of FIRELAVA (animated) and FIRELAV2 (static) textures, in the very same room.
