### ISSUE TITLE
Missing COMP03_9 patch in freedoom1.wad

### ISSUE THREAD

**Issue by ghost** [freedoom/freedoom#520]
While the repo does contain this patch, the actual IWAD freedoom1.wad doesn’t. Even if the original TEXTURE1 / TEXTURE2 lumps don’t reference this patch, I think the patch itself should be still included for the sake of completeness     .

**Comment by Proluiz** [comment]
I've checked this and it's true this patch is inexistent in freedoom.
Just to help with information here's the data that I've collected.

Data collected:
Doom.wad		> Patch present but unused in patch table.
Doom2.wad		> Patch Not present.
Plutonia.wad		> Patch Not present.
Freedoom1.wad	> Patch Not present.
Freedoom2.wad	> Patch Not present.

The said patch on doom:
![COMP03_9](https://user-images.githubusercontent.com/6380147/64303160-36cfb180-cf5d-11e9-893d-3362b5bd1d03.png)

By looking the other patchs from it's family i noticed that patch is identical to Comp02_1:
![COMP02_1](https://user-images.githubusercontent.com/6380147/64303265-b65d8080-cf5d-11e9-963c-a22b74d003cc.png)

This seens easy to fix if necessary.

**Comment by mc776** [comment]
Would this be added to the pnames.txt in /lumps/textures/**doom1** or /lumps/textures/**phase1**?

**Comment by mc776** [comment]
So I've taken a quick look at the build-textures script and my understanding is that it will look at the textures lump and append the patch to the pnames lump *if and only if* that patch is actually used in the textures lump.

Which means that if at any point someone creates a new texture using this patch, it will appear in the pnames lump.

Which means, to address this without creating a completely arbitrary special exception, someone will have to edit a texture so that this patch is used.

It's really not that useful a patch.

I don't think this is something that can or ought to be fixed, given that the absence of this patch doesn't break anything at all.
