### ISSUE TITLE
Remove all of CWolf's contributions

### ISSUE THREAD

**Issue by fragglet** [freedoom/freedoom#528]
Following discussions with @CWolfRU on Doomworld it's clear that he's not happy with his work being available under the Freedoom license. They all need to be removed.

**Comment by NickZ** [comment]
What? Where was this? I don't see any posts on the forums.

**Comment by chungy** [comment]
I would also appreciate a citation, however...

It seems that much (or all?) of his contributions to Freedoom were via GitHub pull requests by himself, which is a bit of an implicit acceptance of the project licensing terms, and I'm hesitant about honoring this type of thing. The pull requests were [over two years ago](https://github.com/freedoom/freedoom/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+author%3Acwolfru+), and I feel like it's too late. His contributions have already made it to released versions of Freedoom, under the project license, and that won't retroactively change.

That being said, if we do remove the contributions, it seems to be relatively minor. We can retain the ones that aren't his original creations, only edits, and even the original creations could be reverted and/or replaced.

**Comment by fragglet** [comment]
Some context is [here](https://www.doomworld.com/forum/topic/99244-i-made-a-thingbut-can-i-post-it/) but I followed up by contacting him privately and still he would not back down from his position, even though I made clear he was leaving no option but to remove his submissions.

Given that he's only made a small number of submissions it shouldn't be too difficult to disentangle.

**Comment by NickZ** [comment]
I don't like the precedent this sets. As far as I'm concerned, when he submitted his assets in PRs, he accepted the licensing terms. He can't claim ignorance about what this would mean for the reuse of assets, it was up to him to read the licensing terms, and we have explained this in the submissions guide. Also, he's been around the Freedoom community for quite a while, and I'm really surprised that he did not know that this was BSD licensed. 

If we go and remove his assets, we open the door to every other former contributor to come back and say that they want their assets pulled as well. This could be disastrous for the project. I don't think we should do it.

**Comment by Talon1024** [comment]
Shame. I really wanted to add his [Lost Soul replacement](https://www.doomworld.com/forum/topic/85258-cwolfs-freedoom-workshop-textures-sprites-something-else/?page=5&tab=comments#comment-1685108) sprites.

But, if everything CWolf contributed has to be removed, here's the stuff I could find:

TGRN (Tall green torch)
TBLU (Tall blue torch)
TRED (Tall red torch)
ELEC (Tech column, edit by Blastfrog)
FSKU (Floating skull rock)
FCAN (Flaming barrel)
CEYE (Evil Eye)
TLMP (Tall tech lamp)
TLP2 (Short tech lamp)

He also contributed some levels as well: C1M9, C2M6, and C2M7

**Comment by mulenmar** [comment]
I realize my input carries little to no weight -- I haven't contributed anything, as I literally only figured out how to replace sprites *today*, and I'm not a lawyer -- but here it is anyway.

**Point One: No Take-Backs**

Once something is released under the BSD license, that's it. It's out there. You might change the license yourself in future versions, if you own the copyright to begin with, and those future versions will be under $(NEW_LICENSE), but **there is no revoking clause for the already released versions.** You think any business would risk using FLOSS if it could be yanked out from underneath them at any time?

CWolf's (Wereknight now, judging by the forum thread) concern about it looking ugly or whatever in a mishmash with other artwork, and his name getting tarnished by people advertising his work being used in it, is covered under "Neither the name of the <organization> nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission." He can pursue whatever legal means he wishes against such derivations. (I don't think "later versions of Freedoom" counts as a "derivative work" any more than a later edition of a book from the same publisher does, but check with a FSF lawyer.)

Using the artwork, separately or in the Freedoom WADs, implicitly agrees to the license, so nobody can accuse the author of endorsing the remix unless he specifically says, "Yeah, I think it's pretty cool, I don't mind putting my stamp of approval on it" or such.

The only legitimate complaint CWolf/Wereknight could possibly have is if someone remixed his work and didn't give credit... you know, like is rampant through the _rest_ of the Doom modding fandom.

Finally, I strongly concur with NickZ's concern about setting precedents. Freedoom is a very slow project as it is without letting disgruntled developers throw a fit and say, "I'm taking my ball and going home!", bleeding away progress.

**Point Two: The Third Option**

If a compromise has to be reached of losing the sprites, but keeping the maps, they honestly aren't nearly as irreplaceable a loss (no disrespect intended -- they're okay, and they  _would_ be missed, but they're much more easily replaced if it comes to that) as entire levels would be.

- I'm not a fan of the current ELECA0 anyway. The one in 0.10.1-2 (packaged in Debian Stable) isn't great either, but it felt more like a *support column* or sturdy electrical conduit. 

- Same goes with the torches, but that's my personal dislike for the less-Doomish and more Quake 2-like theming of the last few years, and isn't really relevant. 

- The old barrel was more consistent with the non-flaming barrel, it just needs the flame touched-up. The current FCAN looks more like a giant Bunsen burner, and thus like a _placed intentionally in-universe_ object rather than the sorta _desperate or uncaring apocalyptic feel_ of a random trash barrel on fire. I don't know offhand of any map that evokes that effect specifically, but now I want to play one. :P

- CEYE... okay, that one is just creepy, and doesn't give the impression of something I should shoot, just stay away from. It wouldn't be too out of place in a Quake 1 mod, imo... but here? It doesn't fit. 

Neither does the v10 version, for that matter -- SIGIL switch-eyes in tiny cubbyholes in a hellish, red environment + red switch-eye replacement = not good  -- though I'd at least shoot that thinking it was a new enemy type if I wasn't familiar with the levels. My immediate idea of using greens instead would be no better (color blindness issue there). I'll think more on it later.

- TLMP doesn't look anything like a lamp to me anyway, and doesn't match light colors that mappers could choose to use in Doom maps. The versions in v0.8 and v0.10 weren't great, per se, but they could be revamped to look less fantasy-esque, maybe with a pair of spiffed-up halogen lights, or a sodium-vapor bulb with futuristic-looking guard around it (open at the bottom, with the support curving up and back down into the pole itself), or something. It wouldn't resemble the Doom2 TLMP, except in light color, and wouldn't look like an unholy crossbreed of Gungnir, a railroad crossing light, and a vibrator.

- TLP2 has the same issue as TLMP, sans the metaphorical Gungnir genes.

**Point 3: Avoiding This Nonsense In The Future**

Require all contributions going forward to include sign-offs stating that the contributer understands that they cannot withdraw contributions unless they discovered that nonfree materials were incorporated, in which case a process of review and proof of this can be carried out, yadda yadda.

Make it an official policy, clearly stated in the contribution page, that no removals will be permitted. Replacements that are upgrades, certainly, but no RIP AND TEAR -- er, I mean, REAVE AND SEVER -- removals just because the author changed xer mind.

**Comment by MatthewTheGlutton** [comment]
Are we really going to go ahead with this??? Given Nicks' points and the 11 thumbs-up reactions and the plain meaning of the BSD licence and the spirit and express intent of the project, should we not just close this?
