### ISSUE TITLE
Doom 3 BFG Edition support

### ISSUE THREAD

**Issue by bryansee** [freedoom/freedoom#529]
When I replaced these wad files that came with Doom 3 BFG Edition with Freedoom, it run without any problems. But when I quit the game, it causes the game to crash.

![rbdoom-3-bfg-20180502-013224-002](https://user-images.githubusercontent.com/2004725/39485080-4f14e2d2-4daa-11e8-8025-ee6f8f1d84b4.png)

I suggest that a Doom 3 BFG Edition support is easily achievable by adding the functionality to change game upon quitting the game.

**Comment by chungy** [comment]
I assume that we are only missing a couple graphics lumps to enable support. Do you know specifically what is required for this?

**Comment by bryansee** [comment]
There's no required couple graphics lumps to enable support on Doom 3 BFG Edition. Only the functionality of quitting the game or change game, much like the Doom BFG wads.

For further information, see:
[https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG](https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG)
[https://github.com/id-Software/DOOM-3-BFG](https://github.com/id-Software/DOOM-3-BFG)

**Comment by Ferk** [comment]
WADs like Freedoom do not really contain "functionality" (at least not before Hexen).
They are just a set of lumps that contain assets, maps and definitions.

What are the differences between the Doom.wad shipped with Doom 3 BFG Edition and the standard Doom.wad? (not in the functionality the engine offers, but the differences in the wads themselves)

**Comment by bryansee** [comment]
The Freedoom wads have, whereas the Doom BFG wads that come with Doom 3 BFG edition don't have.

Still, there should be a functionality on Freedoom that allows the player to change the game in Doom 3 BFG edition upon exiting.

**Comment by DoomeroHispalense** [comment]
Added graphics lumps and their descriptions / transcriptions:

dmenupic.png (titlepic of BFG Edition)
m_acpt.png [accept]
m_can.png [cancel]
m_chg.png [change game]
m_exito.png [Are you sure?]
m_multi.png [multiplayer]

Modified graphics lumps and their transcriptions:

m_gdhigh.png [Fullscreen:]
m_scrnsz.png [Gamepad:]
media0.png (modified medikit)
pstra0.png (modified berserk pack)
stima0.png (modified stimpack)

**Comment by DoomeroHispalense** [comment]
Now, doom2.wad vs. bfgdoom2.wad (ignoring the modified maps, sprites, musics and patches). I am keeping the original capitalization.

cwilv32.png [betray]
dmenupic.png (BFG Edition titlepic)
m_acpt.png [accept]
m_can.png [cancel]
m_chg.png [change game]
m_exito.png [Are you sure?]

cwilv30.png [idkfa]
cwilv31.png [keen]
m_epi1.png [Hell on earth] You could add this one only for freedoom2.wad / freedm.wad with an alternative caption, for example Phase 2 instead of the copyrighted original one. The original Doom II game does not use this, as far I know, while BFG Edition does, so there is no conflict with the original game / executable.
m_epi2.png [No rest for the living] Same as above. I am not sure about the possible alternative caption.
m_episod.png [Which expansion?] Same as above.
m_gdhigh.png [Fullscreen:]
m_scrnsz.png [Gamepad:]

**Comment by DoomeroHispalense** [comment]
Just wait 12 hours, more or less, and download the newest autobuild with these new lumps from here: http://freedoom.soulsphere.org/

**Comment by bryansee** [comment]
Yeah.

**Comment by Ferk** [comment]
Is it working now with the BFG edition?

**Comment by DoomeroHispalense** [comment]
I cannot test it personally. BFG Edition requires yes or yes certain OpenGL extension not supported by my ancient GPU.
