### ISSUE TITLE
Add PWAD distributions containing only maps

### ISSUE THREAD

**Issue by Calinou** [freedoom/freedoom#534]
Distributing PWADs containing only the maps from Freedom (Phase 1, Phase 2 and FreeDM) would make it easier to play these maps using the original Doom IWADs, without having to create those by hand.

I know using Freedoom assets is the intended way to play Freedoom, but some people may prefer using original Doom assets :smiley:

**Comment by chungy** [comment]
Support was removed in https://github.com/freedoom/freedoom/commit/bfb95753bdbf2ae343efd61fd7d9e1e34850aeb1 and I don't think there's any real value in adding it back.

We removed these targets because it creates confusion for a user to download Freedoom ("What file do I get?"), and it's not particularly useful. Freedoom levels are not restricted to using only assets that existed in Doom -- we have several assets that have no equivalent in Doom and many of the levels won't work anyway.

Sorry to say, but this is something you'll have to provide yourself, eg by composing it manually or using [doom-pwads](https://github.com/chungy/doom-pwads/)
