### ISSUE TITLE
DSPOPAIN

### ISSUE THREAD

**Issue by mc776** [freedoom/freedoom#574]
The current DSPOPAIN is very obviously intended for the zombie characters and doesn't sound like either any of the serpentipedes' other sounds or anything one might expect such a creature to make.

This was much less of a problem in Doom since the imps are also basically humanoid, but *also* because Doom's DSPOPAIN was a lot less obviously a man grunting.

I find it tends to really throw off immersion because it's so evocative of those scenes in comedies where they're filming some old (pre-CGI) monster movie and there's a blooper and the guy in the monster suit says something in a totally inappropriate voice for what they're playing as.

I can imagine some kind of hiss-gurgle that might fit both, but I'm sure there are better possibilities...

**Comment by MatthewTheGlutton** [comment]
Interesting, it won't take wav but will take zip.

Anyway, I am most definitely not a sound guy, but here's a crude mix-and-distort based on a couple serpentipede sounds and the current DSPOPAIN that seems to be to strike the balance of being ambiguous between the two.
[dspopain.wav.zip](https://github.com/freedoom/freedoom/files/3639451/dspopain.wav.zip)

(While I like the current DSPOPAIN I think if it's going to err in favour of one it should be in favour of the serpentipede since that's the one we end up hearing far more often than either the zombies or the dark soldier. Incidentally, this proposed distorted tinny thing might fit that fairly well too...)

**Comment by mc776** [comment]
[dspopain.zip](https://github.com/freedoom/freedoom/files/9640155/dspopain.zip)
Here's what I have in my autoloads, a distorted clip from one of the player death sounds from the attic.
