### ISSUE TITLE
Proposal to rename one of the Bringers

### ISSUE THREAD

**Issue by MatthewTheGlutton** [freedoom/freedoom#578]
Pain Bringer and Flame Bringer sound far too much alike for enemies that have nothing to do with each other beyond being both phase 2 enemies.

Is there any prospect of renaming one of them?

**Comment by fragglet** [comment]
Sure. Any suggestions for new names?

**Comment by MatthewTheGlutton** [comment]
I don't suppose Urric ever indicated any preference at all...

I really like "Flame Bringer" for the new archvile since it's also a call back to the metaphorical(?) life-flame for its reviving ability, and I think "Pain Lord" works really well, so the best option in my view is to rename the hell knight only.

An attempt to combine various synonyms for pain and various minor nobility titles brings up nothing satisfactory.

It's a combination of bird, man and plague doctor mask. But they bring pain and death rather than ameliorate or delay it. "Pain Doctor" as a compound all on its own obviously just sounds like a bona fide physician who specializes in ameliorating pain.

It's also heavily armoured? ...which makes it so much harder to avoid "Knight"...

Meanwhile, Pain Bringer itself is a perfectly apt name and is a nice callback to the skill setting, so... more ideas for eye guy, in descending order of my own totally subjective preference:

Wizard
Flame Keeper
Mystic
Outsider
Seer
Eye of Chaos
Pyromancer

**Comment by Ferk** [comment]
Didn't Raymohawk name his Hell Knight "Pestmeister"? though I admit I'm not very fond of that name.

As far as I know Urric didn't suggest any names.
Personally I like the names you proposed.. specially "Flame Keeper" and "Seer", not so much "Outsider". If it's about following Lovecraftian myths, I'd argue that Lovecraft aliens had been in living here in the depths for eons and the life in Earth is just but a byproduct of their influence, it's weird to call "outsider" to someone who has been in the planet longer than us.

**Comment by chungy** [comment]
What if we just call it the **Necromancer**?

**Comment by MatthewTheGlutton** [comment]
Seems like the short list is:
Flame Keeper
Seer
Necromancer

**Comment by fragglet** [comment]
Necromancer sounds good.

**Comment by P41R47** [comment]
new to de git! Hi, everybody!
Congrats on finishing this marvelous sprites, they seem wonderful in motion!
My two coins: Necromancer feels more apt to something more gothic like Blasphemer.
Arch-Vile is a name that surely sounds menacing, while necromancer conjure the image of a weakling magician using dead bodies to attack (ala Diablo II).
Urric, the sprite creator, doesn't name it, but his habdle name comes to sound enigmatic a interestig, so it will be nice to name the monster in his honor. Also i remember reading the thread in doomworld and talking about some kind of psychic or pyrokinetic attack, so i come with the following names:
-Ur-Ic-Niter
-Psycho Igniter
-Ur-DeVoider

**Comment by MatthewTheGlutton** [comment]
I'd rather stay away from wacky manglings of someone's handle if they're not the ones inititating it.

As for "Psycho Igniter", there was a reason for my last pull request for "MAYHEM!" replacing "INSANITY!" as the nightmare skill.

**Comment by P41R47** [comment]
Sorry i'm not very versed on the long story of pull request, can you please elaborate a little what was the reason for replacing the name of the difficult setting. It is ''Insanity'' offensive in some way or something like that?

As for Urric's Arch replacer, well it was a suggestion to name it in his honor for his contribution, but i was also playing with the meaning of the name. Arch-Vile means something like total opposite to the hero. And for the use of the UR in the name, that was because of this:

Albanian
Alternative forms
urë
Etymology
**From Proto-Indo-European *h₁ews- (“to burn”). Compare Latin ūrō.**

Noun
ur ?

ember
Synonyms
prush
 and by this:
Azerbaijani
Etymology
From Common Turkic *ur. Cognate with Turkish ur, etc.

Noun
ur (definite accusative uru, plural urlar)

(pathology, oncology) **neoplasm, tumour**
Synonym: şiş

I know not every player would catch the meaning (as same with arch-vile), but sure it will sound menacing, that why i proposed Ur-Igniter. And now, thinking about the giant eye tumorous thing, i think the following:
Ur-Occh-Niter (Occhio: eye in italian) ----*favorite by now for me* Sound totally enigmatic, alien and frightening.
or Ur-Sighter, Ur-Sawer, Ur-Butcher

**Comment by MatthewTheGlutton** [comment]
I see what you mean now.

I do this kind of thinking a lot for my own projects but for something like Freedoom I think it would be better (and more consistent with the rest of the names) to keep it relatively straightforward with common words.

Something at this level would definitely work for, say, the later critters in a Pokémon clone (the earlier ones e.g. the Kanto starters would be closer to "Serpentipede") but there a lot of the appeal of the core game is in that discovery and nuance rather than "we need a clear label for this particular thing that we're gonna shoot or warn a teammate to shoot". (On that note, the phonetic similarity of "Pain Bringer" and "Flame Bringer" over an imperfect voice chat connection can prove to be a bit of a doozy in the right context)

Absent any major objections (or a sudden suggestion of a name that just pops out as The Name that everyone thinks works perfectly) I might do a PR for "Necromancer" sometime this weekend.

**Comment by P41R47** [comment]
Strightforward, if we want to achieve Freedoom's own personality, if something that we must dodge at all cost.
Just imagine how DOOM would be if Romero & Co. just named the Imp like ''Spitting Fire Humnoid'', or the Cacodemon like ''Floaty Meaty eye''.
I say it again, Necromancer (isn't to strightforward, either) is evocative of something different that what the Arch-Vile represented in the original game. And for the sake of gaining personality, i think we must bounder a little further that just simple and strightforward.
I don't see any other suggestion or opinion.
As for originality, I think that **Ur-Occh**, at least, is a pretty good name for a monster (pokemon developers would love to create a monster around this idea). Wait a little bit with the PR, maybe Fraggle or Chungy, if they got a little time around, can share they opinion with us.

**Comment by chungy** [comment]
I must agree on the simplicity our names have with a combination of plain English and pop culture. The [ur-](https://en.wiktionary.org/wiki/ur-) prefix exists in English but it is not common nor well-known enough to stick in brains; it reaches into the realm of being too clever to be memorable.

Necromancy is fairly well-known in pop culture as relating to magic surrounding the dead. The monster in Doom and Freedoom that this discussion is about is best known for being able to raise monsters back from the dead, which is why I had made the suggestion in the first place.

Given that two others seem to have latched onto the suggestion, I think I'll go ahead and make the change for it. thanks all
