### ISSUE TITLE
Urban Jungle mission can't be finished

### ISSUE THREAD

**Issue by Codified-Vexing** [freedoom/freedoom#591]
In Phase 2, after entering the exit room and defeating all the monsters the mission doesn't end so that the next one can start.
I'm running on Linux Solus OS and I'm using GZDoom with Brutal Doom mod and I have brought along a companion friendly marine from an earlier mission, if that helps understanding the issue.

**Comment by Codified-Vexing** [comment]
Could you tell me how I can check the map number? Is there console command?

**Comment by Codified-Vexing** [comment]
Opening the console says it's Map 16.
The version of Brutal Doom is the one found here: https://www.moddb.com/mods/brutal-doom/downloads/brutal-doom-v21-beta
If I disable the mod the saves don't work and GZDoom will crash to desktop.

**Comment by Codified-Vexing** [comment]
I've disabled the mod and started a new game then used idclev to get to Map16. In that case I managed to finish the level even without defeating all the monsters and dying in the exit room.

**Comment by Codified-Vexing** [comment]
Yes, with BD the level never changes, but without it does.
I've since played all the other levels and this only affects this particular one.

**Comment by MatthewTheGlutton** [comment]
This sounds like a BD bug more than a Freedoom bug, if it works fine in vanilla and presumably most other mods.

**Comment by Catoptromancy** [comment]
MAP16 ends level by crushing icon of sin heads. Maybe needs something simpler. That was a stated goal of freedoom sometime ago, to keep things a bit normal.

**Comment by mc776** [comment]
I've just taken a look at BossBrain.txt in Brutal Doom v21.

It checks for the actor's X position, then its Y position, based on a set of known mapsets for where the boss brain is placed. (If there's a check for which level it is I can't see it based on the DECORATE - the only ACS call I see before the map checks are finished is commented as being about whether you're on a Wolfenstein level.)

For at least a few of these, if the X matches but the Y does not, the actor simply disappears entirely.

For Doom 2, it seems that the actor will set +THRUACTORS, *call A_NoBlocking*, then spawn its other stuff.

If I'm reading this right, BDv21 doesn't seem to support bossbrain death maps at all.

(For comparison, Hideous Destructor handles this exit just fine, but only because it has specific code handling this contingency so the replacement behaviour doesn't happen without a BossEye. I don't know if any active BD forks will have also addressed this.)

Personally I think this is equivalent to someone forgetting to add the boss death/Keen death flags codepointers when replacing those actors wholesale, and thus beyond the scope of Freedoom to work around, so this issue can be closed.
