### ISSUE TITLE
Compatibility problem with Struggle: Antaresian legacy.

### ISSUE THREAD

**Issue by P41R47** [freedoom/freedoom#596]
I tried to play Struggle in crispy with Freedoom 2 as IWAD and it crash without even starting.
Then, i tried it with Struggle and Freedoom 2 as PWADS and it plays normally.
What could be the problem here?
Anybody could try if this problem persist or its just my PC?

**Comment by Proluiz** [comment]
Just a note, here's the following link to the Struggle mod: https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/strg

**Comment by P41R47** [comment]
> Just a note, here's the following link to the Struggle mod: https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/strg

Thanks, Proluiz for the link. I just forget to add it for easy download.
You had the time to try it with Freedoom 2?

**Comment by Proluiz** [comment]
Crispy and chocolate are near the same engine, so I used chocolate. I know it's limit removing mod but I want to know what is the error.

___| Engine used + Freedoom 2|___
Zdoom: No errors
PrBoom: No errors
Chocolate: No issues unless if -Merge is not used, resulting in **R_InitSprites** crash.
--------------------------------------

So far Chocolate can **LOAD** the mod whitout issues, since it's limit removing you can get some visplanes errors, so aside from it this mod has no imcompatibilityes with freedoom.
Remenber to use -Merge command.

A screenshot.
![image](https://user-images.githubusercontent.com/6380147/64216284-9612c080-ce8e-11e9-878b-a55e92e547d1.png)

**Comment by chungy** [comment]
Trying it myself and I don't see problems with it. Make sure you use a correct command, such as:
   crispy-doom -iwad freedoom2.wad -file STRG.wad

**Comment by chungy** [comment]
With apologies I found an error in my testing methodology, I only tested with 0.11.3, while it is indeed broken with the current development HEAD, which I assume you tried.

The PWAD defines a BROWN1 texture that creates a conflict with the A-BROWN4 texture in our IWAD. We have said texture for Plutonia Experiment compatibility, and we can't really solve it without breaking that side of things.

**Comment by P41R47** [comment]
> With apologies I found an error in my testing methodology, I only tested with 0.11.3, while it is indeed broken with the current development HEAD, which I assume you tried.
> 
> The PWAD defines a BROWN1 texture that creates a conflict with the A-BROWN4 texture in our IWAD. We have said texture for Plutonia Experiment compatibility, and we can't really solve it without breaking that side of things.


Yes, sorry Chungy, It didn't cross my mind to try it in a previous version. I tried it with the latest build (freedoom-0.11-367-gd16dcb86) and crispy 5.5.2.
And yes: 
start crispy-doom -iwad freedoom2.wad -merge STRG.wad -deh STRG.deh
exit
thats my .bat file.

So, if we want full compatibilty what we could try?
If we can't fix this without breaking Freedoom 2, Is there a proper way to redefine it inside Struggle texture patch? Seems the easiest solutions.

**Comment by chungy** [comment]
This issue is fixed in 85549628fd108e25311466fcdb467834425bd3da

thanks!
