### ISSUE TITLE
Does anyone actually use the wad-image targets?

### ISSUE THREAD

**Issue by chungy** [freedoom/freedoom#633]
This issue ought to be directed partly at @selliott512 -- I know he uses it (he made it!), but I don't know if anyone else does.

I spent over an hour trying to get wad2image installed in a way that the make targets actually expect. This was complicated because it seems like installing wad2image like a normal program isn't actually supposed to work, and the make file heavily depends on putting it inside Freedoom's script directory (a solution I don't particularly care for). Even after I got something working with a combination of environment variables that are not obvious to me, the utility of it in Freedoom seems... limited. Perhaps a consequence of how I manage the repository, but even things like "compare the latest changed WAD" don't really appear to reliably work like it was expected to work, basing off of file system time stamps that are very suspect to change when checking out different points of the repo history, and not behaving as I would really expect it to behave.

In another case I actually expected it to have: create images of all the Freedoom maps, it seems to be totally lacking (I could script my way to getting that, but... eh).

With apologies to selliot, I think there was a good idea here, but it's buried under many layers of complexity and I am tempted to strip this out of the Freedoom Makefile.

**Comment by Calinou** [comment]
I think generating images is better done using external tooling/scripts anyway, so I'd be fine with removing it. It's not strictly part of the Freedoom project per se.

**Comment by selliott512** [comment]
I'm sorry it's been difficult to use. Maybe i can help. First, a few steps to get it going even if you already did:
```
type -p animate # In ImageMagick.
# An alternative to the following to avoid changing "scripts" is something like 
#   ln -s /home/sle/git/wad2image/bin/wad2image.py /usr/local/bin
# so is symlinked in the path. It can figure it out from there.
ln -s $HOME/git/wad2image scripts # Wherever you have wad2image checked out.

# A tree was moved, which this produces an animated GIF to show.
git checkout e8c621d9e50ca187cc74d2d1c335a0146879bbab -- levels/map05.wad
git reset levels/map05.wad # Modified, not staged, as if it had been copied in.

# Second to last example from "make wad-image-help"
make wad-image-diff WI_VERBOSE=t WI_GIF=t WI_SHOW=t WI_CMD=animate
```
The above should pop up an animated GIF showing that the tree was moved.

As to the motivation - I find working with binary files to be disconcerting since I'm used being able to "diff" changes. If someone claims they made a minor change to a level WAD how do you know what they actually did? Playing through the level seems time consuming. Maybe this is getting to be less of a concern as the level WADs are getting more stable. 

I was under the impression wad2image was going to be integrated with some Freedoom CI build somewhere, but maybe that didn't happen.

As to installing wad2image - I wanted to make it easy for non-technical users to unzip it and run it in place on both Windows and Linux without installing it.

I'm not sure what the best solution is. I understand if you want to rip it out, but maybe a single simplified build target to do just one thing (show the animated GIFs for the currently modified level WADs for example) would be nice.

There are other tools out there to generate images for WADs but they tend to be old, sometimes Windows only and written in strange programing languages, and or interactive (GUI) only, which was my motivation in writing wad2image.

**Comment by fabiangreffrath** [comment]
I don't think the Makefiles should contain anything that isn't of immediate use for building the freedoom IWADs. 

I like the idea of integrating some kind of map-diff as a CI measure, but it should be properly integrated into the present infrastructure. It is actually quite easy to script something suitable using the omgifol library - a map imager is actually among its examples.

**Comment by sirocyl** [comment]
I'm in favor of modularity - leave nonessential features and targets in separate repositories which can be submoduled in (through Git) at one's own option, and enumerate and allow the use of those features at build-time.

Some essential component parts of Freedoom itself may lend to such modularization as well, but I'd scope this down to nonessential components only, for now.

For instance, it might be possible to split off some lump pre-generation scripts used by Freedoom to match strict vanilla compatibility, but those which may be optional or omitted in a non-Freedoom/non-Doom-structured IT1 engine project, or might have been hand-prepared and don't need automation - like, the font-drawing stuff, audio lump preparation such as DMXGUS/GENMIDI, and other ["auxiliary scripts"](https://github.com/freedoom/freedoom/blob/master/BUILD-SYSTEM.adoc#auxiliary-scripts).

**Comment by chungy** [comment]
Let's not overcomplicate things with submodules and such :)

**Comment by chungy** [comment]
Issue no longer relevant with 119f129417a396dec6f5529e2f4549bcf8d535ac
