### ISSUE TITLE
MAP07: only secret on this map is found on start.

### ISSUE THREAD

**Issue by FredBezies** [freedoom/freedoom#640]
Hello.

I'm currently playing freedoom phase 2, and I noticed - using gzdoom - that the only secret in it is found because you start on it!

A very easy to find secret!

**Comment by guynamederick** [comment]
In the original engine, if a level has 0 secrets, the intermission screen will display 0% Secrets after stats are counted. To get around this, some old custom mapsets like Hell Revealed would have their only "secret" at the start or end of the level just so 100% Secrets is displayed in the intermission screen, especially because there are no automap stats or "Secret is revealed!" message in the original engine. Not a bug, though removing it will do no harm and C3M8 in Phase 1 and MAP30 in Phase 2 have no secrets as it is. Might be good to be consistent.

**Comment by FredBezies** [comment]
Thanks for the info. I did not know about this behaviour! Interesting indeed.

**Comment by MatthewTheGlutton** [comment]
Can we add those insta-secrets to C3M8 and Map30 instead?

**Comment by Xindage** [comment]
map07 was changed so this may not be present anymore?
