### ISSUE TITLE
MAP01: light under exit sign

### ISSUE THREAD

**Issue by MatthewTheGlutton** [freedoom/freedoom#643]
There's no obvious light source beaming down from the bottom of the exit sign, but there's an exit-sign-shaped glow on the floor. It looks like an oversight when the surrounding area was darkened.
![map01exitlight](https://user-images.githubusercontent.com/24984517/69122883-c95bf900-0a54-11ea-99ec-472a7e9d1713.png)

**Comment by MatthewTheGlutton** [comment]
I only notice now, looking at this specifically cropped screenshot, that the glow is not just the exit sign protrusion itself but the surrounding glow around the sign that's also visible on (and presumably primarily intended for) the ceiling.

Are different ceiling/floor light values available in vanilla?

**Comment by guynamederick** [comment]
Unfortunately, the original Doom map format only allows one brightness level for a sector, which also means walls and floor steps are as bright as whatever sector they are a line of. In order to have that exit sign be bright, a new sector will have to be made surrounding the sector for the exit sign, and then the brightness level have to be raised so the exit sign doesn't appear dark. I should also mention that the floor below the exit sign has its brightness level change just so there isn't some bright light surrounding a dark shadow from within.

One thing that Plutonia and other vanilla mapsets do is raise a ceiling or lower a floor to a point where the floor will bleed with adjacent sector floors or ceilings. MAP21 of Plutonia has one particular switch that flows bright in a very dark room, but you'll see that the ceilings near the switch aren't bright, just the floor. That is because the ceiling was raised just high enough that you won't see the actual ceiling with the actual brightness level of the sector. Some engines may have trouble rendering these tricks correctly, in fact Double Impact in Freedoom: Phase 1 has these lighting tricks intact like the original mapset.

I suppose the safest options is either to make the exit sign not appear bright at all by having the lighting be darker to match the other sectors, or leave it as it is.

**Comment by AXDOOMER** [comment]
Very good explanation @guynamederick . 

As a perfectionist, it does bother me a little bit that there is this light spot on the ground. If you make its lighting equal to the other sectors, the bright green on the exit sign may be bright enough so it still looks good without extra light.

**Comment by MatthewTheGlutton** [comment]
I just quickly set all those sectors to light 128 and this is how it looks:
![image](https://user-images.githubusercontent.com/24984517/69486627-8908cc00-0e02-11ea-85f2-ac2330f4a0f2.png)

**Comment by AXDOOMER** [comment]
It doesn't look as good without the extra light, sadly we can't have both at the same time. 

I don't think it was an oversight to have this light on the ground. On average, it looked better.

**Comment by MatthewTheGlutton** [comment]
I thought it was self-evidently a completely unmitigated improvement to get rid of the light.

**Comment by Blastfrog** [comment]
It's entirely intentional and I prefer it not be modified, I set it up like that for a reason. @guynamederick summed it up nicely.

**Comment by MatthewTheGlutton** [comment]
Every time I play this map it looks worse to me. The light just doesn't make sense there at all, unless the sign had a flashlight at the bottom that shot a focussed beam right onto that spot on the floor.

**Comment by Blastfrog** [comment]
Okay, it is pretty weird, but I refuse to compromise on having the sign be bright, I meant for it to stand out and contrast against the spooky dark door.

I suppose I could have tiny 1 unit thin triangular slices to brighten them and lower their floor height beneath the surrounding floor height, but I won't leave the lower textures blank because it doesn't play nicely with more limited GL renderers, but certainly something that blends as seamlessly as possible.

On that note, perhaps I should raise the ceiling of that casted light at the very start of the map so that the bright spot on the ceiling isn't as jarring.

**Comment by Blastfrog** [comment]
I addressed this issue (and generally tweaked the map a lot), I'll be making an official submission soon.

**Comment by AXDOOMER** [comment]
I just realized today when playing that the exit sign could have been moved forward by 32 units and the issue with the light would have been solved.

**Comment by Blastfrog** [comment]
But then it wouldn't contrast with the dark ceiling above. I'm not going to be changing it any further, by this point.

https://i.imgur.com/2Ap1iQb.png

**Comment by AXDOOMER** [comment]
Was the sector surrounding the sign made very thin? It would probably look better if the surrounding sector was as big as it originally was. The green lights below the sign are a good improvement :+1:, it does justify the lighting on the floor.

**Comment by Blastfrog** [comment]
Yes, the sector was made extremely thin and actually only on one side, I removed the exit picture on the other side because it technically points the wrong direction. I figured if there isn't a light source on the other sides, they should be dark.

This also allows for the backside to contrast against the bright ceiling behind it when viewed from the exit room. I agree that it's nicer in some ways how it once was, but I think this is better overall. Also I noticed that the attempt at a gradient effect didn't work so well in software mode, the two different light levels are indistinguishable when you're actually up close and near it.
