### ISSUE TITLE
Suggestion: change BEX strings to DEH strings

### ISSUE THREAD

**Issue by Blastfrog** [freedoom/freedoom#681]
One thing that kinda bothers me about using BEX strings means it's impossible for Freedoom to be fully compatible with vanilla, one cannot patch BEX strings into the vanilla EXE. Perhaps we could trim down some that exceed the maximum string length, to ensure that vanilla can display Freedoom's strings.

**Comment by chungy** [comment]
I'm sorry, but there are a few reasons we use BEX instead:

* DEH requires including strings from Doom in order to operate.  Doing it in Freedoom would basically mean violating Doom's copyright and possibly trademarks.
* BEX allows strings to be nearly arbitrary-length, not being limited to the length that Doom strings are.

Freedoom is not really intended to be used with the original vanilla EXEs, even though we otherwise strive for vanilla compatibility. The use of a source port (any of them: Chocolate, PrBoom, GZDoom, etc...) is assumed, and no major port lacks support for BEX patches. We do make sure the BEX doesn't change any game behavior, so nothing is actually _wrong_ when run on the vanilla EXE, besides lacking our own strings.

**Comment by Blastfrog** [comment]
Oh, I entirely forgot that a DEH patch contains the original strings. Yeah, that's quite a roadblock right there. Disappointing, but fair and reasonable.
