### ISSUE TITLE
Remove current Map27 and add proposed Map26 from #689

### ISSUE THREAD

**Issue by mc776** [freedoom/freedoom#693]
"Warped Elementalities" is a miserable room-to-room slog filled with forced backtracking, "what the hell did this switch even do" and tight quarters full of people getting stuck in geometry (that room with the crates with the doors that won't open for another 3 other things to go through is especially obnoxious) and tedious revenant ambushes. It's a few open-areas-filled-with-chaingunners short of a jokewad about everything you can do to make a Doom encounter un-fun.

Example: Just the first ~3-5 minutes of this map are monotonous narrow corridors that you constantly backtrack through hitting switches where you're constantly getting stuck against the beams trying to evade serpentipedes and dark soldiers, with only a short-range weapon, so it's just a test of how straight you can backpedal after each shot so you don't get caught in the geometry, followed by a big open space with no cover where you either retreat and run out of ammo and die to the dark soldiers or you get them to infight with the technospider - and if there's any mod that beefs up either of them to something more convincing you're completely SOL even if you don't retreat.

There are maps that used to be in Freedoom that have been replaced, that better deserve to be in the IWAD.

EDIT: Just to make this abundantly clear: I'm not complaining that the map is *hard*. Plenty of Freedoom maps are hard, including lots of ambushes that I don't even see how you can survive if you don't already know they're coming. The stuff I'm complaining about here just makes things merely *difficult to advance* in a way that just leaves me frustrated and annoyed even after succeeding.

**Comment by MatthewTheGlutton** [comment]
One possibility is to add this map here https://github.com/freedoom/freedoom/pull/689

and replace Map27 with the current Map26, or have Erick's map replace Map27.

Either of those maps is vastly more playable than this one.

**Comment by doomfighter33456** [comment]
amarande made the current map27 and yeah the current map27 is a maze

**Comment by MatthewTheGlutton** [comment]
I posted this issue after seeing what the map was like after the spider encounter for the very first time.

I'd never even had the will to *cheat* past that before, rather than just giving up and playing something else.

Meanwhile, I just got out of playing a few maps of Whispers of Satan and I noticed a couple interesting contrasts:

- there's a really annoying platform-bridge thing on Map10(?) needed to reach the red key. The rest of the map was engaging enough that even after I gave up on that my first thought was to just noclip to it once I confirmed doing so wouldn't break any other sequences.

- there's a cramped crate room in Map02. There's a lot of little crates that let you move around, and the crates themselves are an interesting environment with little quasi-secret things to find. Nothing is spaced in such a way that it's not obvious whether the player can squeeze through.

I'd have posted specific criticisms like this instead of my OP, but the the constant mandatory backtracking masquerading as flow made this map as a whole irredeemable in my view.

**Comment by ibispi** [comment]
Posting this reply to this thread for a friend who refuses to make a Github account:

"I have to agree with OP, «Warped elementality» — despite showing potential — has glaring defects: tedious backtracking; switches which effects are not obvious (forcing more of the mentioned backtracking); numerous close-quarter fights with Dark Soldiers/Deadflare where the main effort is not to get stuck in the level architecture; confusing navigation due to high numbers of teleports.

The worst of it comes at the end: a giant hell themed room full monsters where you have to run like Forrest Gump to hit four switches — one after the other, at the four corners of the world — while avoiding all sort of missles/bullets being shot at you. Oh and there are plenty of Deadflare Balls, so in a few minutes you are swimming in Deadflares and have to use a Double-Barreled Shotgun like a broom to brush them away.

There *are* some good ideas (the cave/alleyway and the pyramid provide good action), but they need to be reworked in a more streamlined map."

**Comment by guynamederick** [comment]
Seeing how this MAP26 #689 has been waiting to be added in for a long while now, this map being considered as a replacement for MAP27 could work too. I could change the file to have the map lump be MAP27 and redo the pull request from there if it's okay.

**Comment by ffaf1** [comment]
I would say that is an excellent choice. In my opinion current MAP26 is quite good (short, compact, actiony) and proposed MAP26 #689 is very good too (nice architecture, secrets, traps).
I very much would love to have them both in freedoom2 and see MAP27 replaced.
