### ISSUE TITLE
Freedoom2 phase 2 issues and bugs found v 0.12.1

### ISSUE THREAD

**Issue by hawkwind3** [freedoom/freedoom#694]
This is a full report of things I found.

FREEDOOM2 Phase 2 v 0.12.1

GENERAL 
	The "chainsaw" angle grinder should really be called a circular saw - it has teeth !
	Maybe a sky height of 240 for sky 1 and 3.

map02 ... 

Note difference in texture lines 753/764 to 1146/1147. One set is lower unpegged and the other not.

map 05 ... 

Lines 953, 959, 968 misaligned.

map 09 ... 

**1. SEMI IMPORTANT ... Sector 2 ( 2 sector 2's ) has a brightness of 208, yet sector 2 where T10 is, has no light source.**
**2. SEMI IMPORTANT ... Wrong ceiling flat for sector 77 and 213 - should be CEIL3_3.**
**3. SEMI IMPORTANT ... Crate area - within sector 35 - needs work.**
4. Suggest remonve "hidden" from line 1569 and replace with "secret".
5. Line 881 could be flagged secret.

map10 ... 

1. Lines 365 etc. not lower unpegged.
2. **IMPORTANT ... MIDTEX back sidedef of lines 1208/1237 missing - BRNSMALC**
3. _**SERIOUS ... If the player falls between vertex 1529 and line 1721, the player is trapped._**
4. Line 839 could be flagged secret.

map11 ... 

1. The switch on line 2402 and 2398 could have had a Y ofset of 64. Looks too high.
2. **IMPORTANT ...The outer wall of sectors 435/438 should be higher - not a good look seeing the lower hemisphere when at sector 432.**
3. Align texture metal1 at line 1933 etc.

map12 ... 

1. **IMPORTANT ... Midtex on lines 773-776 bleeds into the floor/ceiling.**
2. Line 4789 not lower unpegged.

map13 ... 

1. Line 260 needs alignment.
2. Note ceiling of sector 243.

map15 ... 

1. COMPSPAN -at and near sector 561, could use some Y offsetting.
2. Lines 3574, 3573, 3592, 3591, 2796, 2789 could use a Y offset.
3. Sector 807 gives nothing to the easy skill player. It is not even flagged secret.
4. **IMPORTANT ... Sector 486 should have a floor height of -120. ATM, when the lift rises, NUKEDGE is higher than CEIL5_2.**
5. Linedefs 5293,3282,3288 could have been flagged secret.
6. Sectors 145 and 116 should not do damage. And why blocking lines 4095/4070 etc.
7. Issue with crates around sector 259.
8. _**SERIOUS ...When the player uses the switch at line 2421 first and then uses the switch at line 3611; platform rises again, causing render errors. I suggest remove the switch at line 3611 as I don't think it is necessary anyway. Or make it so that the player can just climb out of the "lift pit ".**_
9. **IMPORTANT ... Sector 565 is tagged 28 but no linedef tag 28. Monster at sector 533 cannot teleport. So 100% kills not possible. Simple fix tag sector 565 # 30.** 

map 31 ... 

No exit to map 16. Could easily add one. Or could make the current exit got to map16 and a hidden exit to map32.

map16 .. 

Blocking lines like line 327 would be better for a brick wall to be made, and where line 323 is, a broken wall.

map20 ... 

1. **_SERIOUS ...This wad is not vanilla compatible. Uses silent teleports, scrolling floors and translucent textures._**
2. Ceiling of sectors should probably be DEM1_5. 
3. Wrong ceiling ofsector 413. Should be flat10.
4. **IMPORTANT ... Missing lower back sidedef texture METAL2 on lines 342 and 355.**  Thanks perryprog.

map22 ... 

1.Line 2529 would look better split into 2 lines. One Tekgren4 64 map units, and the new line TEKGREN2 32 map units long. Similar for TEKGREN1 near the exit area.
2. Line 830 could be flagged secret.

map23...
 
1. T489 could use being moved east a bit.
2. Suggestion - Change floor height of sectors 378, 379, 479 and 480 to 232. Currently, the sprites on these sectors render into the ceiling in ogl. Similar for sectors 73/74.
3. Remove lower unpegged from lines 2066, 2082, 2062, 2075.
4. Suggestion - Remove secret from sectors 329 and 488. If running, it is possible to not get the credit.

map 25 ... 

**IMPORTANT ... Sectors 117 and 118 should do damage. When they rise, damage effect is cancelled.**

map26 ... 

1. **IMPORTANT ...T9 and T10 are stuck in each other. Both have the same skill setting.**
2. **IMPORTANT ...Lines 725, 726, 727 and 728 need front side mid tex MIDGRATE.**
3. ROCK2 would look much better on lines 1159/1161.
4. A lot of misaligned GSTONE1.

map27 ... 

1. Lines 1558,  1559 could use x offset.
2. Nothing to suggest that lines 126-128 would reveal a secret. I suggest changing the texture on line 128 only to WOOD7, and negate actions for lines 126, 127.

map28... 

1. Line 2082 etc. could be flagged secret, and 2326, 622.
2. Lines 4594, 4671 could use a Y offset.
3. Lines 5242, 5278 etc need an x offset.
4. Check wall between vertex 5848 and 5849 for alignment.
5. Ceiling of sector 474 would be better for texture GSTONE1 if set higher.
6. **IMPORTANT ...Sectors 147 should do damage. Sector 91 and 115 should not.**

map29 ... 

Lines 882, 879, 875 and 885 could use an X offset of 64.

**Comment by jewellds** [comment]
Hi, thanks for the feedback. I've been working on Map10, and there were a couple of mapping mistakes here I hadn't noticed.

I have a question about "3. Align texture metal1 at line 1933 etc." On every version of the map I have, line 1933 has rock textures, and the metal1 texture isn't used anywhere on the map. What do you mean by this?

**Comment by hawkwind3** [comment]
Hi,

>"3. Align texture metal1 at line 1933 etc."

Sorry about that. It was meant for map11. I will amend the report accordingly.

Thanks for mentioning.

________________________________

**Comment by perryprog** [comment]
Awesome compilation, both this and for phase one. While I'd like to fix a lot of these, I do of course first want to see what any maintainers thoughts are.

To add on to your list:

Map20 has a HOM on the backside of the bridge pillar at the start. Specifically, out the first door, go on the bridge, and do a 180.

**Comment by hawkwind3** [comment]
Hi,

Thanks.

Yes. Map 20. Missing lower texture METAL2 on the back sidedefs of lines 342 and 355.

I will add this and give you credit.

________________________________

**Comment by Blastfrog** [comment]
The thing you commented on with MAP01 is not an issue. Those lines belong to a DM only spawn closet, that is not a secret room. Also, I've been working on a heavy revision of MAP01 for a while, and I've already removed that spawn closet anyhow.

**Comment by hawkwind3** [comment]
Hi Samuel,

You misunderstand me. When i say secret, I mean that the line shows on the map, like a one sided line.
A moot point anyway, since you have removed that multiplayer closet. I will amend accordingly.
Thanks for informing me.

________________________________

**Comment by perryprog** [comment]
And some more things, same deal as my comment for phase one.

>The "chainsaw" angle grinder should really be called a circular saw

Absolutely a very major issue, which I very much agree with. :)

---

- Map9
  - The very first button you have to hit to open up the western door is hard(ish) to find, and hard to walk to. Lots of fun geometry to run into.
  - The red key is not accessible until you pick up the rocket launcher, instead of hitting the button. I don't know if this is intentional, but it is not intuitive to the player that the button would _not_ lower the red key. I would suggest swapping the walk trigger with the switch trigger, which makes more sense for revealing the monster closet anyway.
  - There are three walk triggers for the yellow key, two with the same type. They should be merged to a total for two walk triggers.
- Map11
  - The secret involving shooting line 376 is _really_ hard to find without knowing it's a GR trigger. A use trigger might make more sense.
- Map13
  - The "vent" area at line 1086 doesn't make sense for non-DM. I think the door should be changed to be a stay-open trigger from the inside.
  - For some reason there's a small line that's part of the exit teleporter, which instead of W1 Exit, is WR Teleport to tag 999. It should be changed to be W1 Exit.
- Map15
  - **Important:** The single-use walk trigger, line 163 can easily fail! This can cause a soft-lock that the player needs to reload a save to get out of. Simply drop down past the lift section, and walk over line 163 before you here the "ka-chunk" of the lift. In other words, if the player drops past the lift section and goes right first, it's very easy to have line 163 fail and make it impossible to come out of the "pit" area.
  - Is it intentional for the red key pit to raise instantly? It's a little jarring, and I'm uncertain why it was done that way.
- Map16
  - **Important:** The switch to open the secret is S1 Door when it should be SR Door to prevent the player from being unable to access the secret again. Additionally, there are three separate secret sectors in it causing it to count as three separate secrets. It's also very hard to find the switch, if at all possible. It's also a bit odd that it's just a backpack or backpack + 12 health in easy mode. 
  - Some of the small indoor hallways are hard to walk through.
- Map17
  - Line 439 is missing a front lower texture.
  - Lines 1455–1458 are missing back lower textures.
- Map20
  - As mentioned, this map is not very vanilla friendly. There's also a voodoo doll script that is used to create a cyclic light effect, which of course just does nothing in vanilla.
  - This map is missing a start/exit secret to prevent "0%" secrets from being displayed on exit.
  - There is a 3D bridge effect being done next to sector 430, which is discouraged in Freedoom's README.
- Map21
  - **Important:** The player can cause themselves to become stuck by being slow when leaving the secret in sector 40. There should be a SR trigger on the inside of the door to prevent this.
- Map22
  - It's not very obvious that sector 426 is a door, which is required for level progression.
- Map24
  - More of an opinion, but I find this map a bit too backtrack heavy through many small hallways that are difficult to walk through.
- Map25
  - It's _technically_ (although extremely difficult, and therefore this is a minor issue) possible to get behind the exit and see a missing front texture on line 1392 which should be BRICK6.
- Map26
  - Related to the above issue, line 97 is missing a front upper texture. This is also next to, if not, impossible to see so this is a minor issue.
  - **Important:** Lines 739–741 are using a generalized action, which does nothing on boom-incompatible ports. This does not, however, effect vanilla gameplay as their action (effectively SR Lift) is not actually needed.
- Map27
  - The starting button search hallways are hard to walk through.
  - **Important:** It's possible, and easy, to get stuck between boxes north of the box with sector 158. You must cheat or reload a save to escape.

---

That's all I got. I know some of these issues don't totally line up with each other (that is, the mix of gameplay issues with technical issues), but hopefully that's OK.

**Comment by hawkwind3** [comment]
@**peryprog**  A good compilation. The map15 issue I had already mentioned, as well as map 20. Actually, I'm in the process of fixing map20, so please leave that one to me.

**Comment by hawkwind3** [comment]
Map20 is now fully vanilla. With some changes and fixes as well, too numerous to mention.
[freedoom2_map20_full_vanilla.zip](https://github.com/freedoom/freedoom/files/5088684/freedoom2_map20_full_vanilla.zip)

**Comment by mc776** [comment]
Is there any reason why this one was not included in the "Primary Objectives" of the 0.13 release project?

**Comment by Xindage** [comment]
If you want a release we need to he as stable as possible, so all glitchs must be fixed.

**Comment by mc776** [comment]
Going through this to see what's still outstanding. As before, will post a condensed reply right after this with only the outstanding items.

OP:

Map02
There is no line 1146.

Map09
I tried to fix up the lighting and **yes this area definitely needs to be fixed it looks so much better in my version now.**
**The "needs work" for this crate area is beyond the scope of a minor bugfix.**
**Agreed, southeastern secret door is mistagged as hidden rather than secret.**
**Same with ENE berserk pack secret door.**

Map10
**Lines 365 etc. not lower unpegged.** (Red door leading outside)
**MIDTEX back sidedef of lines 1208/1237 missing - BRNSMALC** (Lights by door leading to the final corridor - you can see the problem if you look back inside)
**Line 839 could be flagged secret.** (South-southeast red armour behind waterfall)
Softlock pit has been fixed.

Map11
High switches have been fixed.
Hard disagree on this "important", the vertiginous height and sense of being lost in the sky is one of my favourite things about this map. *Unfortunately* my previous modifications might have helped address this.
**Grey hexes in corridor around minigunner switch room still misaligned.**

Map12
**MIDSPACE on line 330 bleeds**, but it's only visible from an angle where you'll never see it in normal gameplay. This is exactly what MIDSPCSM is for, though the floor texture could also be changed.
**Line 4787 needs lower unpegged.** (AGM door near the big gappy blue door-like thing)

Map13
**Line 260 needs alignment.**
**ceiling of sector 243 uses wrong flat.**

Map15
**COMPSPAN -at and near sector 561, could use some Y offsetting.**
**Green corridor in the west overlooking the nukage has some mismatched textures.**
**Greyhex near sector 491.** (Little room with the 3 teleport destinations)
Sector 807 previously addressed.
There is no sector 486.
**Linedefs 5293 should be flagged secret.**
Linedefs 3282 and 3288 are monster closets.
**Sectors 145 and 116 should not do damage and should not have invisible blocklines.**
Rising crate platform issues already fixed.
Sector 565 tag already fixed.

Map31
Fixed.

Map16
Previously addressed.

Map20
Vanilla compat has been addressed.
"Ceiling of sectors should be" --???
Sector 413 is now outdoors and correctly ceilinged F_SKY1.
The midtexes around the torches have been removed entirely.

Map22
There is no line 2529.
**Line 830 should be flagged secret.**

Map23
**T489 could use being moved east a bit.** (Candle by doorway in zombie spam corridor - the other candle is not in the way of the egress)
**Floor height of sectors 378, 379, 479 and 480 shoudl be lowered to maybe 232**, to keep the torches from clipping into the ceiling. (Torches by the big "AGM" floor)
**Same with techpillars in the area just after the first long lift.**
**Remove lower unpegged from lines 2066, 2082, 2062, 2075.** ("Door"tracks for the route across those pillars in the southeast - they're actually lifts not doors)
Secret mistagging has been addressed.

Map25
Addressed.

Map26
T9 and T10 are no longer together.
Line references obsolete.
I don't see any glaring (unintentional) misalignments in the green marble stuff now, which is pretty much all new since this issue was posted anyway.

Map27
These are for the old map.

Map28
Line 2082 etc. are monster closets.
**Lines 2326, 622 should be flagged secret.**
**Lines 4594, 4671 need alignment.**
**Scrolling textures around sector 517 need alignment.**
**Doortrack around sector 399 might be messed up.** Really that entire monster closet could use some touchups to deal with sector seam issues.
**Sector 474 ceiling should be raised to match marble brick seams.**
**Sectors 147 should do damage. Sector 91 and 115 should not.**

Map29
**Big green skull pad side textures need realignment.** (Right now they're all starting from the same place which creates this unwanted repeating pattern all around)


Perryprog's reply:

Map09
As far as switch mazes go that first skull switch isn't that bad at all - at least the textures are differentiated enough that you know where you are in that area.
**The red key is not accessible until you pick up the rocket launcher, instead of hitting the button. I don't know if this is intentional, but it is not intuitive to the player that the button would not lower the red key. I would suggest swapping the walk trigger with the switch trigger, which makes more sense for revealing the monster closet anyway.**
**There are three walk triggers for the yellow key, two with the same type. They should be merged to a total for two walk triggers.**

Map11
**The starting room soul sphere secret is virtually impossible to find naturally,** which is especially grating given the level of reward for it. Perryprog suggests using but I don't think that's enough of a hint either.

Map13
I don't interpret that as a vent, more of an emergency exit or something. It *looks* fine in its context and I don't recommend any changes (or at least not anything that could be considered a minor fix - trying to de-abstract one item like this given how the rest of the map looks might be counterproductive).
The mistagged exit pad line is gone now. One of the lines is actually not tagged at all but it's so short it's impossible to cross without hitting the line next to it.

Map15
**Line 163 W1 can fail and result in a softlock.** Make WR or consider re-designing how to get out of that area.
Red card pit addressed.

Map16
**Line 1089 should be SR not S1.** (Switch that opens the secret to the east)
**The cramped hallways in the southwest could be expanded a bit.** In particular the "ribs" in the dead end where the painbro is can be made smaller or even just flush - the textures don't align properly in there anyway, which no one notices because that corridor has nothing of interest in it.

Map17
Line references are obsolete now.
(Incidentally SLADE is throwing a *lot* of missing texture errors at me. It might be worth reviewing these in the future, but those should be posted as new issues and not a reply to this post.)

Map20
Extensive work has been done on this map since this comment was posted. Anything that's still outstanding is best dealt with by posting a new issue.

Map21
Already fixed.

Map22
There is no sector 426.

Map24
Strongly agree, but I'm not marking this bold because fixing this would require a whole new map. (Incidentally if anyone does happen to have a really good late-game map they want to put in FDP2 this is a top priority candidate for replacement.)

Map25
Already fixed.

Map26
Line references obsolete.

Map27
Obsolete, thank goodness!

**Comment by mc776** [comment]
Condensed:

Map09
Starting room lighting is diegetically and logically inconsistent.
Crate maze is a texture alignment disaster.
Southeastern secret door is mistagged as hidden rather than secret.
East-northeast berserk pack secret door needs secret tag.
Red key rocket launcher sequence is needlessly confusing.
There are three walk triggers for the yellow key, two with the same type. They should be merged to a total for two walk triggers.

Map10
Lines 365 etc. not lower unpegged. (Red door leading outside)
MIDTEX back sidedef of lines 1208/1237 missing - BRNSMALC (Lights by door leading to the final corridor - you can see the problem if you look back inside)
Line 839 could be flagged secret. (South-southeast red armour behind waterfall)

Map11
Grey hexes in corridor around minigunner switch room still misaligned.
Starting room soul sphere secret *logically cannot* be solved using ingame hints alone.

Map12
MIDSPACE on line 330 bleeds into the floor.
Line 4787 needs lower unpegged. (AGM door near the big gappy blue door-like thing)

Map13
Line 260 needs alignment.
Ceiling of sector 243 uses wrong flat.

Map15
Line 163 W1 can fail and result in a softlock. Make WR or consider re-designing how to get out of that area.
COMPSPAN -at and near sector 561, could use some Y offsetting.
Green corridor in the west overlooking the nukage has some mismatched textures.
Greyhex near sector 491. (Little room with the 3 teleport destinations)
Linedefs 5293 should be flagged secret.
Sectors 145 and 116 should not do damage and should not have invisible blocklines.

Map16
Line 1089 should be SR not S1. (Switch that opens the secret to the east)
The cramped hallways in the southwest could be expanded a bit. In particular the "ribs" in the dead end where the painbro is can be made smaller or even just flush - the textures don't align properly in there anyway, which no one notices because that corridor has nothing of interest in it.

Map22
Line 830 should be flagged secret.

Map23
Thing 489 (Candle by doorway in zombie spam corridor) should be moved to match its opposite candle.
Floor height of sectors 378, 379, 479 and 480 should be lowered to maybe 232, to keep the torches from clipping into the ceiling. (Torches by the big "AGM" floor)
Techpillars in the area just after the first long lift are also clipping into ceiling.
Remove lower unpegged from lines 2066, 2082, 2062, 2075. ("Door"tracks for the route across those pillars in the southeast - they're actually lifts not doors)

Map28
Lines 2326, 622 should be flagged secret.
Lines 4594, 4671 need alignment.
Scrolling textures around sector 517 need alignment.
Doortrack around sector 399 might be messed up; ceiling could use a border of some sort for transition between inside and outside of monster closet.
Sector 474 ceiling should be raised to match marble brick seams.
Sectors 147 should do damage. Sector 91 and 115 should not.

Map29
Big green skull pad side textures need realignment. Consider also raising or lowering it to match the bricks, or even just changing the texture entirely.
