### ISSUE TITLE
Is extra in-level music still needed?

### ISSUE THREAD

**Issue by actionless** [freedoom/freedoom#744]
according to this page (https://freedoom.github.io/help.html) it is needed, however i didn't found a list for which particular levels it need to be written (and also if you have any overall conceptual ideas for particular levels, ie recommended length, if it should be loop-able, if the style should be more ambient, or more heavy metal, etc)

(i'm interested in contributing midi files, not samples)

**Comment by northivanastan** [comment]
Hey, hope you still care to read this! The only duplicate music track in Phase 1 or 2 has a replacement in a pull request by me. FreeDM might still need new MIDIs, not entirely sure, but a few also have active pull requests.

General style is, I guess "Doom but different?" I'd listen to the soundtrack as well as to the MIDIs changed in those pull requests, and if you think you could improve on anything, write a new MIDI. Failing all of that, just put your MIDI somewhere like [OpenGameArt](https://opengameart.org) so that if Freedoom doesn't use it, it's out there for other people to.

**Comment by Xindage** [comment]
I did read and i asked korp who is mostly leading the music area of the freedoom to reply you but it seems that he forget...
Most of what is there i can really answer since it's not my area of expertise. but if you said that some musics are duplicated and it has pull request to replace them, point me them and i'll check and commit them.

**Comment by northivanastan** [comment]
Those would be #725 for Korp's FreeDM MIDIs and #730 for my E1M5 MIDI

**Comment by Xindage** [comment]
#725 is indeed maintaned by me, korp commision in freedm i'll be merged only when #720 is finished

**Comment by actionless** [comment]
thanks for the reply! since in-level music already complete this issue can be closed

> OpenGameArt 

thanks, i'll check it out
