### ISSUE TITLE
arborix is missing from ﻿the credit file

### ISSUE THREAD

**Issue by fragglet** [freedoom/freedoom#785]
Raymoohawk says that arborix is missing from ﻿the CREDITS file. Can we fix?

**Comment by Xindage** [comment]
give me the details based on the actual credits and i can insert it there. (i picked a example from credit file.)
 ================
N: Colin Phipps
S: cph
E: cph@cph.demon.co.uk
W: http://www.cph.demon.co.uk/
D: binary lumps (playpal, colormap etc)
=================

**Comment by selliott512** [comment]
Adding people to CREDITS sounds like a good idea. Would it be a good idea to proactively pull names from `git log`, or wait for  folks to request it?

**Comment by selliott512** [comment]
I'm happy to add arborix, but there's no reference to `arborix`, case insensitive, in `git log`, any of the main Freedoom files, or in any issue.

**Comment by selliott512** [comment]
The PR I just submitted just has:
```
S: arborix
```

**Comment by mc776** [comment]
> Would it be a good idea to proactively pull names from git log, or wait for folks to request it?

I'm strongly in favour of waiting until someone asks - there's always a risk of deadnaming someone or posting outdated or now-misleading handles or contacts.

So with that in mind I'm going to take the liberty of closing this since technically it is already resolved, but if arborix (or anyone in the credits) wants any information added/updated/corrected/removed please post an issue/post on the discord/email someone/whatever.
