### ISSUE TITLE
My name missing from credits for Map 27 (Warped Elementary)

### ISSUE THREAD

**Issue by DOGB01** [freedoom/freedoom#787]
Credit file should be updated to have DOGB01 as map creator as well as Eric should be there too as he updated and patched some issues.

**Comment by mc776** [comment]
This seems to have fallen through the cracks during the recent update.

Email, website and "N"/walletname? (I think they're all optional as I see muffins.exe only has handle plus what they did listed)

(By the way, since we're on the topic of this map, any thoughts about #798 and #806?)

**Comment by selliott512** [comment]
That's certainly possible. The [recent CREDITS update](https://github.com/freedoom/freedoom/pull/827) was just based on parsing `git log` since 0.27.1. 

Yes, I think the fields are optional.

Hopefully we'll give all issues and PRs before the next release. Then someone (me?) can update CREDITS again.

**Comment by selliott512** [comment]
I've been just crediting top level directories or files that were modified, so `levels` in this case, which addresses the levels being renamed. Currently I have:
```
S: DOGB01
D: levels
```
What should I change or add? Here's an example of a fuller entry:
```
N: Simon Howard
S: fraggle
E: fraggle@soulsphere.org
W: https://soulsphere.org
D: project admin, scripting, build system, textures, sprites, graphics, lumps, manual, patches
```
Most people don't have a web address (`W`), but if you want it I don't see why not.

Incidentally, part of the difficulty probably has to do with people submitting changes on behalf of others, but not setting the author of the git commit, which I've tried to address in `README.adoc` recently.

**Comment by jadenquinn** [comment]
Idk I thought I put my name in the file but I don't think I made it in. Most of my Freedoom contributions aren't even in the wads themselves, they're the high quality soundtracks on YT for it for example, but I did make a couple edits in the maps, E3M3 (new)/E3M4 (old), which I added a pocked full of rockets and stuff in the secret behind the lift that goes to the bottom area of the start circle room.
I also put a soulsphere in E4M8. For some reason it was in the separate double impact wad but not incorporated into Freedoom, which was strange.

Two tiny edits, but like I said most of my contribution to Freedoom is outside of the files themselves.

On the off chance one of you can put my name in since I can't seem to figure it out but did try, I'd be
Name: Jaden LeMieux (iRedMC)
Contact: jadenquinn8@hotmail.com
Contributions: Edits on E3M3 & E4M8, HQ soundtrack


Thanks!

**Comment by selliott512** [comment]
> On the off chance one of you can put my name in since I can't seem to figure it out but did try ...

I just opened [PR 929](https://github.com/freedoom/freedoom/pull/929) based on the information you gave. I can fix it if it's not correct.
