### ISSUE TITLE
Rename Map27

### ISSUE THREAD

**Issue by mc776** [freedoom/freedoom#798]
I was skimming the issues and I saw the typo in #787 "Warped Elementary" and the implications of shooting up a place with "Elementary" in the name suddenly jumped out at me.

This probably won't be the last time someone makes that mistake.

Meanwhile, the actual name "Warped Elementality" is completely meaningless and has nothing to do with the actual map. (I've wanted to suggest a name change for a long time even before the current map stood in this place (see #693 etc.) but this "Elementary" connection was a last straw.)

I think a new name would be good, but it's not appropriate for me to submit a PR unilaterally. (yet)

The map right now is a fairly dark-ish map with a lot of stone and wood and candle-lighting, kinda fancy.

...and has a *lot* of blood.

...and some very blatant cross motifs in significant areas, like how you'd build a cathedral.

~~Some ideas I can brainstorm:
~~Umbral Halls~~
~~Temple of Blood~~
~~Altar of Sacrifice~~
~~Halls of Sacrifice~~
~~Sacerdotum~~
~~Foundation of the World~~
~~Bloodhalls~~
~~Blood Church~~ - yeah no, churches are a pretty common target for spree shooters too~~
EDIT: Best candidate so far: **Palace of Red** as suggested by @Talon1024 

Link to the DEHACKED lump so people can see the adjacent names for context: https://github.com/freedoom/freedoom/blob/master/lumps/dehacked/dehacked.txt

Thoughts?

**Comment by mc776** [comment]
Reading this list again with fresh eyes I think **Halls of Sacrifice** fits best with the surrounding map names...

**Comment by MBYlt** [comment]
So because someone can misread it and get offended, it needs to be changed?

None of the proposed alternatives are any better:

**Umbral Halls** - Could be misread to suggest umbilical cords - that's a yikes.
**Temple of Blood** - Oh, so it's okay to shoot up Jewish places of worship?
**Altar of Sacrifice** - Using the most sacred place in Christian houses of worship for your shooting, eep.
**Halls of Sacrifice** - Wow, what do you have against the creator of the DOOM Bible?
**Sacerdotum** - Could be misread as "Santorum", the name of a gross politician and the gross stuff that comes out after anal sex.
**Foundation of the World** - Are we suggesting that the world is founded upon slaughter? Pretty dark and grim, why must everything be so negative?
**Bloodhalls** - A woman's reproductive organs are no place for games!

Look, I know you're proposing it in good faith and with earnest concern, but that doesn't make it a good idea or an idea that shouldn't be criticized. Once you start worrying about silly stuff like this, there's *no end*.

**Comment by Talon1024** [comment]
How about **Palace of Red**?

**Comment by mc776** [comment]
I'll address all good faith responses so far:

> How about **Palace of Red**?
I was going to object that most of the map is brown and green, but the end-reveal actually makes this a really good idea!

So far my top 3 in descending order:

Palace of Red
Altar of Sacrifice
Foundation of the World

**Comment by mc776** [comment]
...except map25 is already "Red Works" - which isn't really all that red either, except for the blood rivers but it is certainly rather factory-shaped

Come to think of it, though, that *does* make for a neat progression: the "works" of the labyrinthine processing/industrial area, the buffer zone of the "dark depths", then the bougie "palace" that receives the works

**Comment by mc776** [comment]
Got second independent opinion that "temple" is a no-go.

"Palace of Red" is definitely in the lead here.

**Comment by selliott512** [comment]
Although I think that's a reasonable concern since the map really is named "Warped Elementality" the risk of the association you're trying to avoid should be reasonably low. That being said I'm fine with "Palace of Red" - easy to remember, it's the very red map.

I generally don't have strong feelings about map names. I tend to know them by number. So weight my opinion accordingly.
