### ISSUE TITLE
Map27 needs deathmatch starts

### ISSUE THREAD

**Issue by mc776** [freedoom/freedoom#806]
Lest anyone say "you should play freedm": sometimes it's fun to have a deathmatch in a known singleplayer/coop campaign level, to see how differently it plays and try neat setups where you're in the monsters' position. Some mods also have pvp last person standing modes where the monsters are actually meaningful.

Besides, it's a bit jarring and unpolished to have the other maps have the starts but then suddenly have the game abort because map12 has no DM starts even though 13-26 would have played just fine.

**Comment by mc776** [comment]
Editing the title now that #812 takes care of Map12

**Comment by selliott512** [comment]
I added the minimal 4 DM player starts as part of my Eureka cleanup in order to make it happy. It was the only map that did not have them. Feel free to add more, but maybe that's a lower priority.

**Comment by selliott512** [comment]
We can close this?

**Comment by mc776** [comment]
Can we hold off a bit? I was hoping to see if I could do a few things this weekend. This is a fairly large map and only 4 starts is kinda awkward.

Also one of the DM starts is facing the wall...

**Comment by selliott512** [comment]
Hold off with regard to the upcoming release? I'm totally fine with that. There's some last minute cleanup I want to do as well.

**Comment by mc776** [comment]
Oh, right, that.

We definitely don't have enough time to actually test this but at least the PR I've added now shows a bit more of the map in a busy match.

**Comment by selliott512** [comment]
I could only get the door to work from inside the beserk room for gzDoom, but not PrBoom+ and Chocolate Doom. Maybe plain old DR Open door instead of S1 Open and stay /fast ?

You have 13 DM starts exceeding the vanilla limit of 10. It's on the [release checklist](https://github.com/freedoom/freedoom/issues/400). I've reduced the number of DM starts to 10 for all other maps recently. Can you spare 3 DM starts?
