### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by nful2** [freedoom/freedoom#808]
It's been 3 years! When will next version be released? Atleast provide a new version EVERY year.

**Comment by Calinou** [comment]
For reference, here's a list of changes between 0.12.1 and the current `master` branch: https://github.com/freedoom/freedoom/compare/v0.12.1...master

There are definitely enough changes to warrant a new release, but a new release also means the entire game has to be played through in singleplayer, cooperative and deathmatch for QA reasons. This can take a while to happen.

> Atleast provide a new version EVERY year.

I don't think releases should be done under a strict timeline due to the reason mentioned above. There needs to be enough changes accumulated first :slightly_smiling_face:

**Comment by selliott512** [comment]
FWIW I agree that we should have a release, and also that it's not obvious that it needs to be done at a fixed interval.

Some distros just use the latest Freedoom tag, which is v0.12.1, which means that a lot of folks are missing out on everything that's happened since then.

**Comment by rautamiekka** [comment]
Not only the problem of missing out on the new stuff, it just doesn't occur to a very big part of ppl that there could be other ways than the Linux distro repos (in other words: it seems like the project is long dead), but there's also the lack of auto-updates.

**Comment by Mr-Bajs** [comment]
I thought that this project was dead, when i found out about this project. I think most people assume a project is dead, when looking at the latest release date for the latest version.

**Comment by selliott512** [comment]
Concluding that a project is dead based on a years old release date is understandable. I've done that too, but digging deeper it's clear that there have been a lot of activity since 0.12.1 (the last release).

Freedom waxes and wanes. It's pretty active right now, but there have been months between commits in the past. In any case we are close to a release now.
