### ISSUE TITLE
Revert MAP01 to commit 0e70359

### ISSUE THREAD

**Issue by Blastfrog** [freedoom/freedoom#920]
I am very disappointed to see some of the recent changes.

1. Boom light transfer specials were in there for a reason, they make the lighting a bit better in ports that support it. Vanilla ignores it. I intentionally set the map up to look its possible best in both cases.
2. The big impassible gap in the door at the end of the level was supposed to be that big, so you could peer into the destroyed watery section more easily. Narrowing it defeats the purpose.
3. Sector bleeding should not ever be used, as it can cause HOMs or show the sky drum in certain ports.
4. The light on the bottom of the exit sign was meant to justify the light underneath, as it was necessary to avoid a bright seam around the sign's borders which are necessary to light the sides of the sign up at all. Though this is subjective, I also thought it looked rather nice.

Perhaps this is silly of me (particularly considering I based this map on two existing ones) but I feel protective of this map and I don't like these changes being made without consulting me first. These changes are all downgrades, and I'd like them axed. Rebuilding nodes is fine, however.

**Comment by mc776** [comment]
Those ports are doing it wrong and it's their problem. It's time to move on from those.

The exit sign light looked *terrible* that way. The inexplicably bright spotlight on the floor was drawing far more attention than the sign ever did.

Slightly reduced visibility of an unreachable outside area is a lot less immersion-breaking than a clear reminder that you're piloting a perpetually orthogonal inflexible 3'-wide box.

**Comment by KorpKat** [comment]
I frankly dont get whats wrong with the spot of light on the floor, and i dont think its appropiate to just blame the ports for something that was clearly not originally designed in Doom.

I also believe that the flat bleeding trick is not allowed in this project for said reason.

**Comment by mc776** [comment]
While I stand by my statement that this "this is MY content that I made for this so don't change it unless you talk to ME" attitude is completely inappropriate for a contribution to a BSD-licenced project the whole point of which is to create a Free version of the game, I've posted a proposal on Discord that should be a workable compromise - make the exit sign spotlight effect explicitly intentional by adding a flat that works with it, and jamming the door open to 32 units with a tech lamp:
![DOOM03](https://user-images.githubusercontent.com/24984517/227904925-3b8b5a23-cc8b-4df4-95a3-078d09b778bd.png)
![DOOM05](https://user-images.githubusercontent.com/24984517/227904919-89fc0931-9e6c-4b51-b953-b9a39fa2f9c0.png)
![DOOM04](https://user-images.githubusercontent.com/24984517/227904923-0c99f10a-c14b-4e1e-b81d-0700e9b8b63b.png)

**Comment by Xindage** [comment]
are you guys ok with the actual version present in now?
