### ISSUE TITLE
Someone help me uninstalling Freedoom?

### ISSUE THREAD

**Issue by LipoLipeeh** [freedoom/freedoom#923]
I'm layman about coding and all stuff, i just want to go back to play the original Doom 2 Wad without Freedoom, i tried everything even formatting my pc doens't seen to work, like, a fresh new format, even this doesn't remove freedoom from my pc.

![download](https://user-images.githubusercontent.com/129364669/228749283-13040974-a24a-44e1-a9b9-455bf8d89b69.png)

I just open GZdoom without Freedoom and this happens, open Freedom wad, and that's all, dunno what to do.

**Comment by mc776** [comment]
This is a problem with GZDoom and you're best trying to find an answer on the [ZDoom forums](https://forum.zdoom.org/viewforum.php?f=50).

But looking at that I'd suggest trying at least one of the following:
- deleting all your GZDoom files, re-downloading GZDoom and re-installing
- renaming your GZDoom ini files to something like gzdoom-username.i.bak that the program won't recognize, letting it start up with all the defaults

**Comment by Xindage** [comment]
its not a issue with gzdoom or with freedoom as well:
gzdoom is capable of handling several iwads as seen here:
![image](https://user-images.githubusercontent.com/6380147/228813945-605715f1-3e20-4173-a220-cccda90f1669.png)
and by "default" sometimes gzdoom and derivated ports comes pre-packaged with freedoom, the issue is "gzdoom" is not locating doom2.wad. now lets see some solutions:
1º: do you have doom2 steam version? if yes, download it on your pc and gzdoom will automatically see it and allow you to choose the iead tp play.
2º: never use "[x] never ask me again" switch, if you enabled it its going to be hard to disable.
3º: if you dont have doom from steam, put the iwads content inside gzdoom directory
