### ISSUE TITLE
Some suggestions for episode 1

### ISSUE THREAD

**Issue by nful2** [freedoom/freedoom#979]
[Suggestions.zip](https://github.com/freedoom/freedoom/files/11654953/Suggestions.zip) - for suggestions, See the text file in the zip. The images are according to the numbers in the text file. Some skipped numbers are videos:

14. https://github.com/freedoom/freedoom/assets/100768714/db0f2179-bcc6-41ed-a41f-ba6bad4262a6

(22) e1m1 jumping from lift - https://github.com/freedoom/freedoom/assets/100768714/53070603-e53a-4ba4-853a-2ca847e33bdb, e1m1 lowering shotgun - https://github.com/freedoom/freedoom/assets/100768714/eb6dfcad-29cc-49f4-874c-296e5944859e

**Comment by mc776** [comment]
Yeah no.

Trimming the gameplay elements down to absolute bare necessities = shitty, forgettable map.

And the secret sound is based on your sourceport, vanilla doesn't even tell you when you've found a secret.

**Comment by mc776** [comment]
LFS = Lines flagged to prevent discovery of secret using automap.
SFG = See first comment on this github issue.
DM = This is for deathmatch.
:( = Well that's just *your* opinion, man!


e1m9
1. They seem more a hazard for the player than the monsters, though you could also use them against anything chasing you through from the other side of the lift. They're valid.
2. LFS
5. It's actually a processing area for corpses. **I might change this to clarify that.**

e1m4
3. SFG
4. Things are really hectic in the surrounding areas and that break is good.

e1m5
**6. May consider after release.**
7. Please no more unopenable doors ffs.
8-9. There are levels after this one.

e1m6
10. SFG
11. Are you actually having trouble seeing those stairs? (Not insulting, genuine question - I recently made an edit to E2M4 precisely because I kept running past the stairs out of an area) If not then there's no reason to expect the player to skip them.
12. Reundant armour isnt' much worse than redundant health. 🤷
13. There are levels after this one.
**14. That does look odd. Lines 181 etc. should be unflagged - 2255 etc. together with 483 should be able to keep the next wave from advancing prematurely. **
15. LFS

e1m7
16. SFG
17. SFG
18. DM

e1m8
**19. Exit torch should be there at all skills or none.** However, it does appear already flagged as present for medium for me???


e1m1
20. SFG
**21. Honestly a big powerup that early feels really out of place.**
22. SFG
23. In other skill levels it's a stimpack which may or may not be picked up. It's obvious enough that it shouldn't warrant a secret flag.

e1m2
24. :(

25. Not IWAD issue, sound provided by sourceport.

**Comment by mc776** [comment]
Re: point 19, should that torch even be there? How do you get up there to light it? How does the pad receive anything without destroying it? What's it even for? Is this some kind of reference or backstory I'm missing?

**Comment by nful2** [comment]
Just realized I am sort of 'minimalist'. Will look from different perspectives before suggesting anything in future.

**Comment by nful2** [comment]
@mc776 should I avoid zip files?

**Comment by Xindage** [comment]
gonna comment some stuffs
18 - Intended, down there is a deathmatch arena, they're separated from the main map. (vanilla doom deathmatch requires exit if they're not in the same area as the coop area, because the old deathmatch wont end after some get x amount of frags)
25 - same as mcc comented, vanilla doom dont have secret reveal noise. its from sourceport.
about e1m1 i fell the same way as you, i think e1m1 is way too complex for starting level, but i'm not in care of episode 1 to do anything about it.
