### ISSUE TITLE
Skill levels are mostly missing.

### ISSUE THREAD

**Issue by Catoptromancy** [freedoom/freedoom#99]
Even after many updates this is still an on-going issue that many maps need to be more tested and adjusted.

**Comment by milasudril** [comment]
I thought one could write a script for estimating difficulty in a DOOM level, based on statistics collected from levels found at `/idgames`, such as monster frequency, the amount of ammo, health, and power-ups, at different difficulties. Then one could use similar distributions. Possibly, this approach is biased to more difficult levels. I have seen some impossible mods there.

**Comment by LavenderMoon** [comment]
It might be better to use Doom 1 and 2 as a basis for analysis, or maybe even use Doom 1 as a basis for Freedoom: Phase 1 and Doom 2 as a basis for Freedoom: Phase 2. That way, the results won't be so skewed towards the skill level of players who've been with Doom for years.

**Comment by Catoptromancy** [comment]
This issue is mainly a reminder. 

I am doing skill testing and adjustments, though slowly. My rough guideline is for Freedoom to be decently harder than original iwads for id (people on the forums generally thought this was best also). -skill 4 should be a hard but reasonable challenge for modern doom players. -skill 3  should be about the same as id's iwads, a decent challenge for any type of gamer. -skill 2 is made with -skill 1 in mind since both use same tags. -skill 2 should only be a challenge for non-gamers, and skill 1 should just be very easy. Skill 2 I also try to keep the "feel" of the harder skills for example: in certain situations instead of removing a cyberdemon, I add an invulnerability sphere and a little more ammo. 

The only way to really determine the skill balance I am looking for is to play them and adjust them manually.

**Comment by fragglet** [comment]
I already wrote a script to estimate difficulty a couple of years ago; you can see the output here:

http://www.doomworld.com/vb/freedoom/61904-is-freedoom-too-hard/

I'm not sure how useful it was. I think it's harder to estimate difficulty than people assume.

**Comment by chungy** [comment]
Do you still have the script?

**Comment by fragglet** [comment]
Had a look but I can't find it now.

**Comment by chungy** [comment]
Hmm, that's too bad, but I don't think the metrics that you used would be too hard to do over again. :)

**Comment by milasudril** [comment]
An improvement would obviously be to add monster speed. The archvile should have a higher rating due to its ability to respawn monsters. Other things to look for is crossing line triggers a trap, and small "bridges" over poison where the player has to move slowly to not fall down. There are some of the latter things in Psychophobia.

**Comment by Danfun64** [comment]
What do you mean "add monster speed"? The freedoom project isn't trying to change the gameplay at all, just provide a free content replacement, and before you ask, the only thing the freedoom .bex files do is change strings to free equivalents. Monster stats aren't change in the slightest.

**Comment by rjy** [comment]
I think he means "Add monster speed [to your script as part of the
metric for difficulty estimation]"

-- 
http://rjy.org.uk/

**Comment by milasudril** [comment]
@rjy Exactly. The fastest original monster is Archvile, right? The "blood ghost" example was to demonstrate the impact of speed. In particular, that monster has 600 hp, but only meele attack. Other aspects: Monster size (a large monster is easier to hit). Maybe Cacco is a bit harder because it can fly. 

A general rating formula can look something like

sum(attack_rating)*monster_hitpoints/monster_size

where attack_rating contains measurements of all possible attacks. Basically it should measure the number of hit points per second issued by each attack. A starting approach is to take

attack_rating=projectile_speed*projectile_range*projectile_damage

For a meele attack monster, speed can be taken as the speed of the monster. For hitscan attacks, the formula obviously brakes, otherwise the zombie would win over cyberdemon, which is not the case. So there has to be something else in this case.

**Comment by kaadmy** [comment]
Been thinking about doing some mapping for Freedoom; is there anything that I should know first?

**Comment by Catoptromancy** [comment]
This is not just about skill levels, but gameplay/fun. There are already tools that list items and monster counts and should be good enough to determine if a monster or item appears too early or too late.

**Comment by kaadmy** [comment]
I know about simple level design/progression for the complete set of levels, and I noticed that Phase 1's E1M1 shouldn't have the raising platform in the nukage(too complicated and too easy to fall for beginners), and E1M2 is WAY too complicated, and the spawn looks nearly identical to Hangar.

**Comment by milasudril** [comment]
Too many traps in E1M2

**Comment by kaadmy** [comment]
Yep.

**Comment by Catoptromancy** [comment]
Skills are mostly done now. Old maps have been further tested and adjusted. New maps are tested as they come in.
